export default {
    warp: { frequency: 0.003, amplitude: 4, octaves: 2, sampleOffset: [320, 88] },
    palette: { base: [6, 16, 10], floorBase: [4, 20, 12], wallBase: [14, 9, 5] },
    motifs: [
        {
            type: "baseMetal",
            structure: { frequency: 0.007, octaves: 2, rgbDelta: [1, 5, 2] },
            grain: { frequency: 0.45, octaves: 2, amplitude: 0.4 },
            surfaceMask: "all",
            blendMode: "add",
            opacity: 0.85,
        },
        { type: "filterHSV", surfaceMask: "all", hueShift: 88, saturation: 4.2, value: 0.72, blendMode: "add", opacity: 1 },
        { type: "surfaceGrain", surfaceMask: "floor", frequency: 0.14, axis: "horizontal", axisStretch: 0.1, octaves: 2, amplitude: 2.4, tint: [0.3, 1.4, 0.45], blendMode: "multiply", opacity: 0.6 },
        { type: "translate", x: 0, y: 0, coordinateMode: "evalAndWarped" },
        {
            type: "concentricRings",
            surfaceMask: "floor",
            coordinateSpace: "warped",
            frequency: 0.016,
            ringWidth: 0.1,
            peak: 6,
            offset: [0, 0],
            tint: [2.0, 2.4, 0.5],
            blendMode: "screen",
            opacity: 0.75,
        },
        {
            type: "wallHorizontalBevel",
            surfaceMask: "wall",
            bands: 5,
            ribFill: 0.58,
            highlightPeak: 9,
            shadowPeak: 13,
            coreWidth: 0.2,
            corePeak: 7,
            coreTint: [2.4, 1.5, 0.35],
            snakeStrength: 0.35,
            blendMode: "add",
            opacity: 0.88,
        },
        { type: "wallCircuitSnake", surfaceMask: "wall", frequency: 0.026, threshold: 0.19, peak: 14, tint: [2.8, 2.0, 0.45], wiggleAmplitude: 16, octaves: 2, opacity: 0.8, blendMode: "add" },
        { type: "wallLighting", surfaceMask: "wall", power: 1.15, topDarken: 20, coolBias: 0.9, blendMode: "multiply", opacity: 1 },
        { type: "filterHSV", surfaceMask: "all", hueShift: 0, saturation: 1.12, value: 1.04, blendMode: "replace", opacity: 1 },
    ],
    animation: {
        stages: [
            {
                frames: 36,
                durationMs: 2400,
                tracks: [
                    { targetPath: "motifs[3].x", startValue: 0, endValue: 18, easing: "easeInOutSine" },
                    { targetPath: "motifs[3].y", startValue: 0, endValue: 10, easing: "easeInOutSine" },
                    { targetPath: "motifs[2].amplitude", startValue: 2.4, endValue: 3.6, easing: "easeOutSine" },
                    { targetPath: "motifs[4].frequency", startValue: 0.016, endValue: 0.03, easing: "easeInOutSine" },
                    { targetPath: "motifs[4].peak", startValue: 6, endValue: 11, easing: "easeOutQuad" },
                    { targetPath: "motifs[5].snakeStrength", startValue: 0.35, endValue: 0.55, easing: "easeInOutSine" },
                    { targetPath: "motifs[5].corePeak", startValue: 7, endValue: 11, easing: "easeOutSine" },
                    { targetPath: "motifs[6].peak", startValue: 14, endValue: 20, easing: "easeOutCubic" },
                    { targetPath: "motifs[8].hueShift", startValue: 0, endValue: 10, easing: "linear" },
                    { targetPath: "motifs[8].value", startValue: 1.04, endValue: 1.12, easing: "easeOutSine" },
                ],
            },
            {
                frames: 32,
                durationMs: 2000,
                tracks: [
                    { targetPath: "motifs[3].x", startValue: 18, endValue: 44, easing: "easeInCubic" },
                    { targetPath: "motifs[3].y", startValue: 10, endValue: 22, easing: "easeInCubic" },
                    { targetPath: "motifs[2].amplitude", startValue: 3.6, endValue: 5.2, easing: "easeInOutQuad" },
                    { targetPath: "motifs[4].frequency", startValue: 0.03, endValue: 0.052, easing: "easeInOutCubic" },
                    { targetPath: "motifs[4].ringWidth", startValue: 0.1, endValue: 0.038, easing: "easeInOutQuad" },
                    { targetPath: "motifs[4].peak", startValue: 11, endValue: 20, easing: "easeOutQuint" },
                    { targetPath: "motifs[5].snakeStrength", startValue: 0.55, endValue: 0.92, easing: "easeOutCubic" },
                    { targetPath: "motifs[5].corePeak", startValue: 11, endValue: 19, easing: "easeOutQuint" },
                    { targetPath: "motifs[6].peak", startValue: 20, endValue: 32, easing: "easeOutExpo" },
                    { targetPath: "motifs[6].threshold", startValue: 0.19, endValue: 0.11, easing: "easeInOutSine" },
                    { targetPath: "motifs[6].wiggleAmplitude", startValue: 16, endValue: 30, easing: "easeOutSine" },
                    { targetPath: "motifs[8].hueShift", startValue: 10, endValue: 26, easing: "linear" },
                    { targetPath: "motifs[8].saturation", startValue: 1.12, endValue: 1.48, easing: "easeOutSine" },
                    { targetPath: "motifs[8].value", startValue: 1.12, endValue: 1.28, easing: "easeOutCubic" },
                ],
            },
            {
                frames: 36,
                durationMs: 2600,
                tracks: [
                    { targetPath: "motifs[3].x", startValue: 44, endValue: 0, easing: "easeInOutCubic" },
                    { targetPath: "motifs[3].y", startValue: 22, endValue: 0, easing: "easeInOutCubic" },
                    { targetPath: "motifs[2].amplitude", startValue: 5.2, endValue: 2.4, easing: "easeInOutSine" },
                    { targetPath: "motifs[4].frequency", startValue: 0.052, endValue: 0.016, easing: "easeInOutSine" },
                    { targetPath: "motifs[4].ringWidth", startValue: 0.038, endValue: 0.1, easing: "easeInOutQuad" },
                    { targetPath: "motifs[4].peak", startValue: 20, endValue: 6, easing: "easeInQuint" },
                    { targetPath: "motifs[5].snakeStrength", startValue: 0.92, endValue: 0.35, easing: "easeInOutSine" },
                    { targetPath: "motifs[5].corePeak", startValue: 19, endValue: 7, easing: "easeInCubic" },
                    { targetPath: "motifs[6].peak", startValue: 32, endValue: 14, easing: "easeInExpo" },
                    { targetPath: "motifs[6].threshold", startValue: 0.11, endValue: 0.19, easing: "easeInOutSine" },
                    { targetPath: "motifs[6].wiggleAmplitude", startValue: 30, endValue: 16, easing: "easeInSine" },
                    { targetPath: "motifs[8].hueShift", startValue: 26, endValue: 0, easing: "linear" },
                    { targetPath: "motifs[8].saturation", startValue: 1.48, endValue: 1.12, easing: "easeInSine" },
                    { targetPath: "motifs[8].value", startValue: 1.28, endValue: 1.04, easing: "easeInOutCubic" },
                ],
            },
        ],
    },
};
