import { describe, it } from "node:test";
import assert from "node:assert/strict";
import { KineticSpatialFrame } from "../Libraries/Spatial/spatial.js";
import { LIBRARY_COLLISION_DEFAULTS } from "../Libraries/Physics/physics.js";
import { advanceKineticSleep } from "../Libraries/Physics/physics.js";
import { clearActiveKineticBodySlab, writeKineticLinkNeighbors, resetKineticLinkNeighborArena } from "../Libraries/Physics/physics.js";
import { kineticDynamicSlab, entityRefs } from "../Core/engineMemory.js";
import { mockKineticBody, mockCircleProp, assignPhysIdWithPose } from "./harness/kineticTickHarness.js";
import { createKineticAdmitTestState } from "./harness/stateFactories.js";
import { createFractureWorld } from "./harness/fractureHarness.js";
import { WorldProp } from "../Libraries/Props/props.js";
const SLEEP_FRAMES = LIBRARY_COLLISION_DEFAULTS.kineticSleepFrames;
const mockGrid = { minX: -500, maxX: 500, minY: -500, maxY: 500 };
const mockState = createKineticAdmitTestState();
describe("active kinetic bodies", () => {
    it("syncActiveKineticBodies keeps only awake bodies", () => {
        const frame = new KineticSpatialFrame(50);
        const awake = mockKineticBody(false);
        const asleep = mockKineticBody(true);
        frame._pushKineticEid(awake._physId); frame._pushKineticEid(asleep._physId);
        frame.syncActiveKineticBodies();
        assert.equal(kineticDynamicSlab.activePhysCount, 1);
        assert.equal(entityRefs[kineticDynamicSlab.activePhysIds[0]], awake);
        assert.equal(kineticDynamicSlab.activePhysCount, 1);
        assert.equal(kineticDynamicSlab.activePhysIds[0], awake._physId);
    });
    it("activateKineticBody wakes and appends once", () => {
        const frame = new KineticSpatialFrame(50);
        const prop = mockKineticBody(true);
        frame._pushKineticEid(prop._physId);
        frame.syncActiveKineticBodies();
        assert.equal(kineticDynamicSlab.activePhysCount, 0);
        frame.activateKineticBody(prop._physId);
        assert.equal(prop.isSleeping, false);
        assert.equal(kineticDynamicSlab.activePhysCount, 1);
        assert.equal(kineticDynamicSlab.activeSlot[prop._physId], 0);
        assert.equal(kineticDynamicSlab.activeSlot[prop._physId], 0);
        frame.activateKineticBody(prop._physId);
        assert.equal(kineticDynamicSlab.activePhysCount, 1);
        assert.equal(kineticDynamicSlab.activeSlot[prop._physId], 0);
    });
    it("scheduled activation batches island peers on flush", () => {
        const frame = new KineticSpatialFrame(50);
        frame.resetFrame(mockGrid);
        const head = mockCircleProp(0, 0, 10);
        const tail = mockCircleProp(20, 0, 10);
        assignPhysIdWithPose(head, 0);
        assignPhysIdWithPose(tail, 1);
        frame.insertEntity(head, 0);
        frame.insertEntity(tail, 1);
        resetKineticLinkNeighborArena();
        writeKineticLinkNeighbors(head._physId, [tail._physId]);
        writeKineticLinkNeighbors(tail._physId, [head._physId]);
        head.isSleeping = true;
        tail.isSleeping = true;
        frame._pushKineticEid(head._physId); frame._pushKineticEid(tail._physId);
        frame.syncActiveKineticBodies();
        assert.equal(kineticDynamicSlab.activePhysCount, 0);
        frame.scheduleKineticActivation(head._physId);
        assert.equal(kineticDynamicSlab.activePhysCount, 0);
        frame.flushScheduledKineticActivations();
        assert.equal(kineticDynamicSlab.activePhysCount, 2);
        assert.equal(kineticDynamicSlab.activeSlot[head._physId], 0);
        assert.equal(kineticDynamicSlab.activeSlot[tail._physId], 1);
        assert.equal(kineticDynamicSlab.activePhysCount, 2);
        assert.equal(kineticDynamicSlab.activePhysIds[0], head._physId);
        assert.equal(kineticDynamicSlab.activePhysIds[1], tail._physId);
    });
    it("sleeping kinetic body drops out of active list on next sync", () => {
        const frame = new KineticSpatialFrame(50);
        const prop = mockKineticBody(false);
        frame._pushKineticEid(prop._physId);
        frame.syncActiveKineticBodies();
        assert.equal(kineticDynamicSlab.activePhysCount, 1);
        for (let i = 0; i < SLEEP_FRAMES; i++) advanceKineticSleep(prop._physId, true);
        assert.equal(prop.isSleeping, true);
        frame.syncActiveKineticBodies();
        assert.equal(kineticDynamicSlab.activePhysCount, 0);
        assert.equal(kineticDynamicSlab.activePhysCount, 0);
    });
    it("begin() keeps admitted prop physId across consecutive frames", () => {
        const world = createFractureWorld();
        const frame = new KineticSpatialFrame(50);
        const prop = new WorldProp(0, 0, "box", 0);
        world.worldProps.push(prop);
        frame.begin(world);
        const physId = prop._physId;
        frame.begin(world);
        assert.equal(prop._physId, physId);
    });
    it("admitKineticProp makes mid-frame spawns visible to neighbor queries", () => {
        const frame = new KineticSpatialFrame(50);
        frame.resetFrame(mockGrid);
        clearActiveKineticBodySlab();
        const anchor = mockCircleProp(0, 0, 10);
        frame.insertEntity(anchor, 0);
        frame._pushKineticEid(anchor._physId);
        frame._nextPhysId = 1;
        const fragment = mockCircleProp(24, 0, 8);
        frame.admitKineticProps([fragment], mockState);
        const count = frame.ensureNeighborEids(anchor);
        const eids = anchor._neighborEids;
        let found = false;
        for (let i = 0; i < count; i++) if (eids[i] === fragment._physId) found = true;
        assert.ok(found);
        assert.ok(kineticDynamicSlab.activeSlot[fragment._physId] >= 0);
        assert.equal(kineticDynamicSlab.activeSlot[fragment._physId], kineticDynamicSlab.activeSlot[fragment._physId]);
    });
    it("mid-frame admit syncs slab pose so spawns are not at origin", () => {
        const frame = new KineticSpatialFrame(50);
        frame.resetFrame(mockGrid);
        clearActiveKineticBodySlab();
        const anchor = mockCircleProp(0, 0, 10);
        frame.insertEntity(anchor, 0);
        frame._pushKineticEid(anchor._physId);
        frame._nextPhysId = 1;
        const fragment = mockCircleProp(240, 180, 8);
        frame.admitKineticProps([fragment], mockState);
        assert.equal(kineticDynamicSlab.x[fragment._physId], 240);
        assert.equal(kineticDynamicSlab.y[fragment._physId], 180);
        assert.equal(fragment.x, 240);
        assert.equal(fragment.y, 180);
    });
    it("admitKineticProp reindexes props after geometry or position changes", () => {
        const frame = new KineticSpatialFrame(50);
        frame.resetFrame(mockGrid);
        clearActiveKineticBodySlab();
        const mover = mockCircleProp(0, 0, 10);
        frame.insertEntity(mover, 0);
        frame._pushKineticEid(mover._physId);
        frame._nextPhysId = 1;
        const witness = mockCircleProp(200, 0, 8);
        frame.admitKineticProps([witness], mockState);
        {
            const count = frame.ensureNeighborEids(witness);
            const eids = witness._neighborEids;
            let found = false;
            for (let i = 0; i < count; i++) if (eids[i] === mover._physId) found = true;
            assert.equal(found, false);
        }
        mover.x = 200;
        frame.admitKineticProps([mover], mockState);
        {
            const count = frame.ensureNeighborEids(witness);
            const eids = witness._neighborEids;
            let found = false;
            for (let i = 0; i < count; i++) if (eids[i] === mover._physId) found = true;
            assert.ok(found);
        }
    });
    it("activateKineticBody skips island peers missing _physId", () => {
        const frame = new KineticSpatialFrame(50);
        frame.resetFrame(mockGrid);
        const head = mockCircleProp(0, 0, 10);
        const tail = mockCircleProp(20, 0, 10);
        frame.insertEntity(head, 0);
        frame.insertEntity(tail, 1);
        resetKineticLinkNeighborArena();
        writeKineticLinkNeighbors(head._physId, [1]);
        delete tail._physId;
        frame._pushKineticEid(head._physId);
        frame._pushKineticEid(1);
        frame.syncActiveKineticBodies();
        frame.activateKineticBody(head._physId);
        assert.equal(kineticDynamicSlab.activePhysCount, 1);
        assert.equal(entityRefs[kineticDynamicSlab.activePhysIds[0]], head);
        assert.equal(kineticDynamicSlab.activePhysIds[0], head._physId);
        frame._ensureActive(1, false);
        frame.reindexActiveKineticBodies();
        assert.equal(kineticDynamicSlab.activePhysCount, 1);
        assert.equal(entityRefs[kineticDynamicSlab.activePhysIds[0]], head);
    });
    it("scheduled activation wakes direct link neighbors only on long chains", () => {
        const frame = new KineticSpatialFrame(50);
        frame.resetFrame(mockGrid);
        const head = mockCircleProp(0, 0, 10);
        const mid = mockCircleProp(20, 0, 10);
        const tail = mockCircleProp(40, 0, 10);
        assignPhysIdWithPose(head, 0);
        assignPhysIdWithPose(mid, 1);
        assignPhysIdWithPose(tail, 2);
        frame.insertEntity(head, 0);
        frame.insertEntity(mid, 1);
        frame.insertEntity(tail, 2);
        resetKineticLinkNeighborArena();
        writeKineticLinkNeighbors(head._physId, [mid._physId]);
        writeKineticLinkNeighbors(mid._physId, [head._physId, tail._physId]);
        writeKineticLinkNeighbors(tail._physId, [mid._physId]);
        head.isSleeping = true;
        mid.isSleeping = true;
        tail.isSleeping = true;
        frame._pushKineticEid(head._physId); frame._pushKineticEid(mid._physId); frame._pushKineticEid(tail._physId);
        frame.syncActiveKineticBodies();
        frame.scheduleKineticActivation(head._physId);
        frame.flushScheduledKineticActivations();
        assert.equal(head.isSleeping, false);
        assert.equal(mid.isSleeping, false);
        assert.equal(tail.isSleeping, true);
        assert.equal(kineticDynamicSlab.activePhysCount, 2);
        assert.equal(kineticDynamicSlab.activePhysCount, 2);
    });
});
