import assert from "node:assert/strict";
import { describe, it } from "node:test";
import { loadPropAssets } from "../Libraries/Props/loadPropAssets.js";
import { resetKineticConstraintIds } from "../Libraries/Motion/kineticConstraints.js";
import { getOrderedChainMemberIds } from "../Libraries/Sandbox/chainLinks.js";
import { applySnakeGameConfig, getSnakeGameConfig } from "../Libraries/Game/snake/snakeGameConfig.js";
import { registerAgentInstance } from "../Libraries/Game/snake/snakeAgentSession.js";
import { getCirclePropRadius } from "../Libraries/Props/propScale.js";
import { resolveFleeAgentForwardDir, spawnFleeAgent } from "../Libraries/Game/snake/fleeAgent/spawnFleeAgent.js";
import { createFleeAgentInstance } from "../Libraries/Game/snake/fleeAgent/FleeAgentInstance.js";
import { createSnakeGameHarnessState, wireSnakeTestGame, registerSnakeTestInstance, primeSnakeHeadVision } from "./harness/snakeGameHarness.js";
import { spawnSnakeChain } from "../Libraries/Game/snake/snakeScene.js";
import { attachKineticTestTickFromState } from "./harness/kineticTickHarness.js";
import { gatherKineticContactPairs, kineticContactBuffer, resolveKineticContactPassWithPairs } from "../Libraries/Spatial/collision/kineticContactSolver.js";
import { applyKineticContactSideEffects } from "../Libraries/Spatial/collision/kineticContactSideEffects.js";
import { resolveSnakeCombatFromContacts } from "../Libraries/Game/snake/snakeCombat.js";
loadPropAssets();

function spawnVisibleSnakeThreat(state, snakeGame, { col, row }, segmentCount = 6) {
    const chain = spawnSnakeChain(state, { col, row }, { segmentCount, spacing: 12, segmentRadius: 2, linkSlack: 0.1, faction: "snake", exportType: "snake" });
    registerSnakeTestInstance(state, snakeGame, { headId: chain.chain.head.id, spawnGroupId: chain.chain.spawnGroupId });
    chain.chain.head.faction = "snake";
    return chain;
}

describe("flee agent spawn", () => {
    it("spawns one flee_ball with chain head", async () => {
        resetKineticConstraintIds(1);
        const { state } = await createSnakeGameHarnessState();
        wireSnakeTestGame(state);
        applySnakeGameConfig({ startRadius: 2 });
        const pack = spawnFleeAgent(state, { col: 10, row: 10 });
        assert.equal(pack.members.length, 1);
        assert.equal(pack.head.type, "flee_ball");
        assert.equal(pack.head.shape.type, "Circle");
        assert.ok(pack.head.strategy?.canChain);
        assert.deepEqual(getOrderedChainMemberIds(state, pack.head.id), [pack.head.id]);
        assert.equal(state.kinetic.kineticConstraints.length, 0);
    });

    it("initializes facing to flee forward", async () => {
        resetKineticConstraintIds(5);
        const { state } = await createSnakeGameHarnessState();
        wireSnakeTestGame(state);
        applySnakeGameConfig({ startRadius: 2, growDirX: -1, growDirY: 0 });
        const forward = resolveFleeAgentForwardDir();
        const pack = spawnFleeAgent(state, { col: 10, row: 10 });
        assert.ok(Math.abs(pack.head.facing - Math.atan2(forward.y, forward.x)) < 1e-4);
    });

    it("applies fleeAgent roll speed from snake config", async () => {
        resetKineticConstraintIds(9);
        const { state } = await createSnakeGameHarnessState();
        wireSnakeTestGame(state);
        applySnakeGameConfig({ startRadius: 2, fleeAgent: { maxSpeed: 120, accel: 400 } });
        const pack = spawnFleeAgent(state, { col: 10, row: 10 });
        assert.equal(pack.head.strategy.groundNav.maxSpeed, 120);
        assert.equal(pack.head.strategy.groundNav.accel, 400);
        assert.equal(pack.head.type, "flee_ball");
    });

    it("scales ball radius to snake start radius", async () => {
        resetKineticConstraintIds(2);
        const { state } = await createSnakeGameHarnessState();
        wireSnakeTestGame(state);
        applySnakeGameConfig({ startRadius: 2 });
        const pack = spawnFleeAgent(state, { col: 10, row: 10 });
        assert.equal(getCirclePropRadius(pack.head), 2);
        assert.equal(pack.head.radius, 2);
    });
    it("starts, ticks, and flees from a visible snake threat", async () => {
        resetKineticConstraintIds(3);
        const { state } = await createSnakeGameHarnessState();
        wireSnakeTestGame(state);
        applySnakeGameConfig({ startRadius: 2 });
        const snakeGame = state.sandbox.snakeGame;
        const pack = spawnFleeAgent(state, { col: 10, row: 10 });
        const instance = createFleeAgentInstance(state, { headId: pack.head.id, spawnGroupId: pack.spawnGroupId });
        registerAgentInstance(snakeGame, "flee_agent", instance);
        instance.start(state);
        assert.equal(instance.intent.getMode(), "explore");
        instance.tick(state, 16);
        assert.ok(instance.intent.getDestination());
        spawnVisibleSnakeThreat(state, snakeGame, { col: 10, row: 14 }, 6);
        primeSnakeHeadVision(state, pack.head, getSnakeGameConfig().visionRange);
        instance.tick(state, 16);
        assert.equal(instance.intent.getMode(), "flee");
    });
    it("shatters flee agent on predator snake head ram", async () => {
        applySnakeGameConfig({ splitImpulseThreshold: 30 });
        resetKineticConstraintIds(4);
        const { state } = await createSnakeGameHarnessState();
        wireSnakeTestGame(state);
        const snakeGame = state.sandbox.snakeGame;
        const pack = spawnFleeAgent(state, { col: 10, row: 10 });
        const instance = createFleeAgentInstance(state, { headId: pack.head.id, spawnGroupId: pack.spawnGroupId });
        registerAgentInstance(snakeGame, "flee_agent", instance);
        instance.start(state);
        applySnakeGameConfig({ splitImpulseThreshold: 30, growDirX: 1 });
        const predator = spawnSnakeChain(state, { col: 12, row: 10 }, { segmentCount: 5, spacing: 12, segmentRadius: 2, linkSlack: 0.1, faction: "snake", exportType: "snake" });
        applySnakeGameConfig({ splitImpulseThreshold: 30, growDirX: -1 });
        registerSnakeTestInstance(state, snakeGame, { headId: predator.chain.head.id, spawnGroupId: predator.chain.spawnGroupId });
        snakeGame.registry.aliveByHeadId.set(predator.chain.head.id, { headId: predator.chain.head.id, species: "snake", lifecycle: "alive" });
        predator.chain.head.faction = "snake";
        const predatorHead = predator.chain.head;
        const prey = pack.head;
        predatorHead.vx = -80;
        predatorHead.vy = 0;
        prey.vx = 10;
        prey.vy = 0;
        predatorHead.x = prey.x + prey.radius + predatorHead.radius - 2;
        predatorHead.y = prey.y;
        const props = [...predator.chain.members, prey];
        const tick = attachKineticTestTickFromState(state, props, 50);
        const pairs = gatherKineticContactPairs(tick);
        resolveKineticContactPassWithPairs(tick, pairs);
        applyKineticContactSideEffects(tick, kineticContactBuffer);
        resolveSnakeCombatFromContacts(state, tick.frame, kineticContactBuffer, snakeGame);
        assert.equal(instance.lifecycle, "dead");
        assert.ok(snakeGame.registry.deadHeadIds.has(pack.head.id));
        assert.equal(state.entityRegistry.getLive(pack.head.id), null);
    });

    it("sprinting flee dies to predator snake head ram", async () => {
        applySnakeGameConfig({ splitImpulseThreshold: 30 });
        resetKineticConstraintIds(6);
        const { state } = await createSnakeGameHarnessState();
        wireSnakeTestGame(state);
        const snakeGame = state.sandbox.snakeGame;
        const pack = spawnFleeAgent(state, { col: 10, row: 10 });
        const instance = createFleeAgentInstance(state, { headId: pack.head.id, spawnGroupId: pack.spawnGroupId });
        registerAgentInstance(snakeGame, "flee_agent", instance);
        instance.start(state);
        instance.sprinting = true;
        applySnakeGameConfig({ splitImpulseThreshold: 30, growDirX: 1 });
        const predator = spawnSnakeChain(state, { col: 12, row: 10 }, { segmentCount: 5, spacing: 12, segmentRadius: 2, linkSlack: 0.1, faction: "snake", exportType: "snake" });
        applySnakeGameConfig({ splitImpulseThreshold: 30, growDirX: -1 });
        registerSnakeTestInstance(state, snakeGame, { headId: predator.chain.head.id, spawnGroupId: predator.chain.spawnGroupId });
        snakeGame.registry.aliveByHeadId.set(predator.chain.head.id, { headId: predator.chain.head.id, species: "snake", lifecycle: "alive" });
        predator.chain.head.faction = "snake";
        const predatorHead = predator.chain.head;
        const prey = pack.head;
        predatorHead.vx = -80;
        predatorHead.vy = 0;
        prey.vx = 10;
        prey.vy = 0;
        predatorHead.x = prey.x + prey.radius + predatorHead.radius - 2;
        predatorHead.y = prey.y;
        const props = [...predator.chain.members, prey];
        const tick = attachKineticTestTickFromState(state, props, 50);
        const pairs = gatherKineticContactPairs(tick);
        resolveKineticContactPassWithPairs(tick, pairs);
        applyKineticContactSideEffects(tick, kineticContactBuffer);
        resolveSnakeCombatFromContacts(state, tick.frame, kineticContactBuffer, snakeGame);
        assert.equal(instance.lifecycle, "dead");
        assert.ok(snakeGame.registry.deadHeadIds.has(pack.head.id));
        assert.equal(state.entityRegistry.getLive(pack.head.id), null);
    });

    it("sprinting flee in flee mode rams snake body and splits the victim", async () => {
        applySnakeGameConfig({ splitImpulseThreshold: 30, minAliveSegmentCount: 3 });
        resetKineticConstraintIds(7);
        const { state } = await createSnakeGameHarnessState();
        wireSnakeTestGame(state);
        const snakeGame = state.sandbox.snakeGame;
        const pack = spawnFleeAgent(state, { col: 10, row: 10 });
        const instance = createFleeAgentInstance(state, { headId: pack.head.id, spawnGroupId: pack.spawnGroupId });
        registerAgentInstance(snakeGame, "flee_agent", instance);
        instance.start(state);
        instance.sprinting = true;
        instance.intent = { getMode: () => "flee" };
        const victim = spawnSnakeChain(state, { col: 20, row: 10 }, { segmentCount: 5, spacing: 12, segmentRadius: 2, linkSlack: 0.1, faction: "snake", exportType: "snake" });
        registerSnakeTestInstance(state, snakeGame, { headId: victim.chain.head.id, spawnGroupId: victim.chain.spawnGroupId });
        const victimMembers = getOrderedChainMemberIds(state, victim.chain.head.id);
        const struckBody = state.entityRegistry.getLive(victimMembers[2]);
        const fleeHead = pack.head;
        fleeHead.vx = 80;
        fleeHead.vy = 0;
        struckBody.vx = -5;
        struckBody.vy = 0;
        fleeHead.x = struckBody.x - fleeHead.radius - struckBody.radius + 2;
        fleeHead.y = struckBody.y;
        const props = [...victim.chain.members, fleeHead];
        const tick = attachKineticTestTickFromState(state, props, 50);
        const pairs = gatherKineticContactPairs(tick);
        resolveKineticContactPassWithPairs(tick, pairs);
        applyKineticContactSideEffects(tick, kineticContactBuffer);
        resolveSnakeCombatFromContacts(state, tick.frame, kineticContactBuffer, snakeGame);
        assert.ok(kineticContactBuffer.count >= 1);
        assert.equal(instance.lifecycle, "alive");
        assert.ok(getOrderedChainMemberIds(state, victim.chain.head.id).length < victimMembers.length);
    });
});
