import assert from "node:assert/strict";
import { describe, it } from "node:test";
import { resetKineticConstraintIds } from "../Libraries/Motion/kineticConstraints.js";
import { applySnakeGameConfig } from "../Libraries/Game/snake/snakeGameConfig.js";
import { registerAgentInstance } from "../Libraries/Game/snake/snakeAgentSession.js";
import { spawnGameAgentChain } from "../Libraries/Game/snake/spawnAgentChain.js";
import { createAgentInstance } from "../Libraries/Game/snake/AgentInstance.js";
import { AGENT_PROFILE } from "../Libraries/AI/agents/agentProfile.js";
import { getPropVisualTint } from "../Libraries/Color/visualOverride.js";
import { getAgentIdentity, setAgentIdentity } from "../Libraries/AI/identity/agentIdentity.js";
import { createAgentMetabolism, getAgentHunger, setAgentHunger, tickAgentMetabolism } from "../Libraries/Game/snake/agentMetabolism.js";
import { getCirclePropRadius } from "../Libraries/Props/propScale.js";
import { resolveSnakeEatRadius } from "../Libraries/Game/snake/snakeGameConfig.js";
import { deriveSprintIntent } from "../Libraries/AI/agents/deriveSprintIntent.js";
import { getSnakeGameConfig } from "../Libraries/Game/snake/snakeGameConfig.js";
import { getAgentProfile } from "../Libraries/AI/agents/agentProfile.js";
import { AGENT_DECISION_PROFILE } from "../Libraries/AI/agents/gameDecisionContext.js";
import { spawnSnakeChain } from "../Libraries/Game/snake/snakeScene.js";
import { createSnakeGameHarnessState, wireSnakeTestGame, spawnSnakeFoodShardAtCell, primeSnakeHeadVision, registerSnakeTestInstance } from "./harness/snakeGameHarness.js";
import { colRowToIndex } from "../Libraries/Spatial/grid/GridUtils.js";
function stampWall(grid, col, row) {
    grid.grid[colRowToIndex(col, row, grid.cols)] = 1;
}
function spawnVisibleSnakeThreat(state, snakeGame, { col, row }, segmentCount = 6) {
    const chain = spawnSnakeChain(state, { col, row }, { segmentCount, spacing: 12, segmentRadius: 2, linkSlack: 0.1, faction: "snake", exportType: "snake" });
    registerSnakeTestInstance(state, snakeGame, { headId: chain.chain.head.id, spawnGroupId: chain.chain.spawnGroupId });
    chain.chain.head.faction = "snake";
    return chain;
}
describe("flee agent metabolism", () => {
    it("pins hunger at zero instead of dying", () => {
        applySnakeGameConfig({ agentProfiles: { flee_agent: { metabolism: { hungerDrainMs: 1000, foodValue: 0.5 } } } });
        const metabolism = createAgentMetabolism(getAgentProfile(AGENT_PROFILE.flee));
        setAgentHunger(metabolism, 0.1);
        tickAgentMetabolism(metabolism, 500, 1);
        assert.equal(getAgentHunger(metabolism), 0);
        tickAgentMetabolism(metabolism, 500, 1);
        assert.equal(getAgentHunger(metabolism), 0);
    });
    it("sprint multiplies hunger drain", () => {
        applySnakeGameConfig({ agentProfiles: { flee_agent: { metabolism: { hungerDrainMs: 1000, foodValue: 0.5 }, sprint: { hungerDrainMultiplier: 2 } } } });
        const metabolism = createAgentMetabolism(getAgentProfile(AGENT_PROFILE.flee));
        setAgentHunger(metabolism, 1);
        tickAgentMetabolism(metabolism, 500, 2);
        assert.ok(getAgentHunger(metabolism) < 0.5);
    });
    it("refills hunger from shard pickup while seeking food", async () => {
        resetKineticConstraintIds(30);
        const { state } = await createSnakeGameHarnessState();
        const { snakeGame } = wireSnakeTestGame(state);
        applySnakeGameConfig({ startRadius: 2, agentProfiles: { flee_agent: { metabolism: { hungerDrainMs: 60_000, foodValue: 0.4 } } } });
        const pack = spawnGameAgentChain(state, { col: 10, row: 10 }, "flee_agent");
        const instance = createAgentInstance(state, { profileId: AGENT_PROFILE.flee, head: pack.head, spawnGroupId: pack.spawnGroupId });
        registerAgentInstance(snakeGame, "flee_agent", instance);
        instance.start();
        setAgentHunger(instance.metabolism, 0.2);
        spawnSnakeFoodShardAtCell(state, { col: 10, row: 10 }, { foodValue: 0.4 });
        primeSnakeHeadVision(state, pack.head, getSnakeGameConfig().shared.visionRange);
        instance.tick( 16);
        assert.equal(instance.intent.getMode(), "seek_food");
        assert.ok(getAgentHunger(instance.metabolism) >= 0.6);
    });
    it("seeks visible food when hungry", async () => {
        resetKineticConstraintIds(32);
        const { state } = await createSnakeGameHarnessState();
        const { snakeGame } = wireSnakeTestGame(state);
        applySnakeGameConfig({ startRadius: 2 });
        const pack = spawnGameAgentChain(state, { col: 10, row: 10 }, "flee_agent");
        const instance = createAgentInstance(state, { profileId: AGENT_PROFILE.flee, head: pack.head, spawnGroupId: pack.spawnGroupId });
        registerAgentInstance(snakeGame, "flee_agent", instance);
        instance.start();
        setAgentHunger(instance.metabolism, 0.2);
        const food = spawnSnakeFoodShardAtCell(state, { col: 14, row: 10 });
        primeSnakeHeadVision(state, pack.head, getSnakeGameConfig().shared.visionRange);
        instance.tick( 16);
        assert.equal(instance.intent.getMode(), "seek_food");
        assert.equal(instance.intent.getTargetId(), food.id);
    });
    it("eats food once terminal homing reaches pickup range", async () => {
        resetKineticConstraintIds(36);
        const { state } = await createSnakeGameHarnessState();
        const { snakeGame } = wireSnakeTestGame(state);
        applySnakeGameConfig({ startRadius: 2, agentProfiles: { flee_agent: { metabolism: { hungerDrainMs: 60_000, foodValue: 0.4 } } } });
        const pack = spawnGameAgentChain(state, { col: 10, row: 10 }, "flee_agent");
        const instance = createAgentInstance(state, { profileId: AGENT_PROFILE.flee, head: pack.head, spawnGroupId: pack.spawnGroupId });
        registerAgentInstance(snakeGame, "flee_agent", instance);
        instance.start();
        setAgentHunger(instance.metabolism, 0.2);
        const food = spawnSnakeFoodShardAtCell(state, { col: 14, row: 10 }, { foodValue: 0.4 });
        primeSnakeHeadVision(state, pack.head, getSnakeGameConfig().shared.visionRange);
        instance.tick( 16);
        assert.equal(instance.intent.getMode(), "seek_food");
        assert.ok(instance.intent.getDestination()?.lockOnTarget, "food seek should lock onto the shard for terminal homing");
        const foodLive = state.entityRegistry.getLive(food.id);
        const eatRadius = resolveSnakeEatRadius(getSnakeGameConfig(), getCirclePropRadius(pack.head));
        pack.head.x = foodLive.x + eatRadius + 2;
        pack.head.y = foodLive.y;
        instance.tick( 16);
        assert.ok(state.entityRegistry.getLive(food.id));
        pack.head.x = foodLive.x + eatRadius - 0.5;
        pack.head.y = foodLive.y;
        instance.tick( 16);
        assert.equal(state.entityRegistry.getLive(food.id), null);
        assert.ok(getAgentHunger(instance.metabolism) > 0.55);
    });
    it("does not seek food hidden behind walls", async () => {
        resetKineticConstraintIds(33);
        const { state } = await createSnakeGameHarnessState();
        const { snakeGame } = wireSnakeTestGame(state);
        applySnakeGameConfig({ startRadius: 2, agentProfiles: { flee_agent: { initialHunger: 1 } } });
        const pack = spawnGameAgentChain(state, { col: 10, row: 10 }, "flee_agent");
        const instance = createAgentInstance(state, { profileId: AGENT_PROFILE.flee, head: pack.head, spawnGroupId: pack.spawnGroupId });
        registerAgentInstance(snakeGame, "flee_agent", instance);
        instance.start();
        for (let col = 11; col <= 17; col++) stampWall(state.obstacleGrid, col, 10);
        const food = spawnSnakeFoodShardAtCell(state, { col: 18, row: 10 });
        primeSnakeHeadVision(state, pack.head, getSnakeGameConfig().shared.visionRange);
        instance.tick( 16);
        assert.equal(instance.intent.getMode(), "explore");
        assert.ok(state.entityRegistry.getLive(food.id));
        assert.ok(getAgentHunger(instance.metabolism) > 0.99);
    });
    it("flee overrides seek_food when threat is severe", async () => {
        resetKineticConstraintIds(34);
        const { state } = await createSnakeGameHarnessState();
        const { snakeGame } = wireSnakeTestGame(state);
        applySnakeGameConfig({ startRadius: 2, agentProfiles: { flee_agent: { sprint: { fleeSeverity: 0.3 } } } });
        const pack = spawnGameAgentChain(state, { col: 10, row: 10 }, "flee_agent");
        const instance = createAgentInstance(state, { profileId: AGENT_PROFILE.flee, head: pack.head, spawnGroupId: pack.spawnGroupId });
        registerAgentInstance(snakeGame, "flee_agent", instance);
        instance.start();
        setAgentHunger(instance.metabolism, 0.2);
        spawnSnakeFoodShardAtCell(state, { col: 14, row: 10 });
        primeSnakeHeadVision(state, pack.head, getSnakeGameConfig().shared.visionRange);
        instance.tick( 16);
        assert.equal(instance.intent.getMode(), "seek_food");
        spawnVisibleSnakeThreat(state, snakeGame, { col: 10, row: 13 }, 6);
        primeSnakeHeadVision(state, pack.head, getSnakeGameConfig().shared.visionRange);
        instance.tick( 16);
        assert.equal(instance.intent.getMode(), "flee");
    });
    it("keeps base color while sprinting flee", async () => {
        resetKineticConstraintIds(31);
        const { state } = await createSnakeGameHarnessState();
        const { snakeGame } = wireSnakeTestGame(state);
        applySnakeGameConfig({ startRadius: 2, agentProfiles: { flee_agent: { sprint: { fleeSeverity: 0.3 } } } });
        const pack = spawnGameAgentChain(state, { col: 10, row: 10 }, "flee_agent");
        setAgentIdentity(pack.head.id, { name: "Bolt", color: "#7ad4ff" });
        const instance = createAgentInstance(state, { profileId: AGENT_PROFILE.flee, head: pack.head, spawnGroupId: pack.spawnGroupId });
        registerAgentInstance(snakeGame, "flee_agent", instance);
        instance.start();
        assert.equal(instance.baseTint, "#7ad4ff");
        spawnVisibleSnakeThreat(state, snakeGame, { col: 10, row: 13 }, 6);
        primeSnakeHeadVision(state, pack.head, getSnakeGameConfig().shared.visionRange);
        instance.tick( 16);
        assert.equal(instance.intent.getMode(), "flee");
        assert.equal(instance.sprinting, true);
        assert.equal(instance.baseTint, "#7ad4ff");
    });
    it("deriveSprintIntent wants sprint on lethal flee when hunger allows", () => {
        applySnakeGameConfig({ agentProfiles: { flee_agent: { sprint: { fleeSeverity: 0.5, sprintFleeMinHunger: 0.1 } } }, shared: { lethalThreatRange: 48 } });
        const sprint = getAgentProfile(AGENT_DECISION_PROFILE.flee).sprint;
        const ctx = { threatState: { lethal: true, severity: 1 }, hungerTier: "hungry", foodFraction: 0.5 };
        assert.equal(deriveSprintIntent("flee", ctx, sprint).want, true);
        assert.equal(deriveSprintIntent("explore", ctx, sprint).want, false);
    });
});
