/** Motif field metadata for the tile lab profile editor. */

export const LAYER_OPTIONS = [
    { id: "all", label: "All" },
    { id: "floor", label: "Floor only" },
    { id: "wall", label: "Wall only" },
    { id: "wallFace", label: "Wall face" },
    { id: "wallCell", label: "Wall cell top" },
];

export const BLEND_OPTIONS = [
    "replace", "add", "multiply", "screen", "overlay", 
    "hard-light", "soft-light", "color-dodge", "color-burn", "difference"
];

/** Context motifs shift coordinates for layers below; they are not painted or blended. */
export function isContextMotif(type) {
    return type === "translate";
}

export const MOTIF_TYPES = {
    translate: {
        label: "Translate",
        defaults: {
            type: "translate",
            x: 0,
            y: 0,
            coordinateMode: "evalAndWarped",
        },
        fields: [
            { path: "x", label: "X", min: -2000, max: 2000, step: 5 },
            { path: "y", label: "Y", min: -2000, max: 2000, step: 5 },
            {
                path: "coordinateMode",
                label: "Coordinate space",
                options: [
                    { value: "evalAndWarped", label: "Eval + warped" },
                    { value: "evalOnly", label: "Eval only" },
                ],
            },
        ],
    },
    baseMetal: {
        label: "Base metal",
        defaults: {
            type: "baseMetal",
            structure: { frequency: 0.0025, octaves: 1, rgbDelta: [3, 3, 4] },
            grain: { frequency: 0.18, octaves: 1, amplitude: 1 },
            opacity: 1,
            blendMode: "add",
        },
        fields: [
            { path: "structure.frequency", label: "Structure freq", min: 0.0005, max: 0.02, step: 0.0005 },
            { path: "structure.octaves", label: "Structure octaves", min: 1, max: 4, step: 1 },
            { path: "structure.rgbDelta.0", label: "Struct R Δ", min: -12, max: 12, step: 1 },
            { path: "structure.rgbDelta.1", label: "Struct G Δ", min: -12, max: 12, step: 1 },
            { path: "structure.rgbDelta.2", label: "Struct B Δ", min: -12, max: 12, step: 1 },
            { path: "grain.frequency", label: "Grain freq", min: 0.05, max: 2, step: 0.05 },
            { path: "grain.amplitude", label: "Grain amp", min: 0, max: 6, step: 0.5 },
            { path: "opacity", label: "Opacity", min: 0, max: 1, step: 0.05 },
        ],
    },
    deckPlates: {
        label: "Deck plates",
        defaults: {
            type: "deckPlates",
            cellWorldSize: 16,
            plateCells: 2,
            plateRows: 2,
            groutWidth: 0.045,
            groutPeak: 11,
            groutTint: [-6, -6, -5],
            plateVariation: 3,
            jitterOffset: [0, 0],
            rivetSpacing: 16,
            rivetInset: 4,
            rivetRadius: 0.018,
            rivetPeak: 5,
            rivetTint: [2, 4, 5],
            blendMode: "multiply",
            opacity: 0.85,
        },
        fields: [
            { path: "cellWorldSize", label: "Cell world px", min: 8, max: 64, step: 1 },
            { path: "plateCells", label: "Plate cells (W)", min: 1, max: 8, step: 1 },
            { path: "plateRows", label: "Plate cells (H)", min: 1, max: 8, step: 1 },
            { path: "groutWidth", label: "Grout width", min: 0.01, max: 0.15, step: 0.005 },
            { path: "groutPeak", label: "Grout peak", min: 0, max: 20, step: 1 },
            { path: "plateVariation", label: "Plate jitter", min: 0, max: 10, step: 0.5 },
            { path: "rivetSpacing", label: "Rivet spacing (0=off)", min: 0, max: 32, step: 1 },
            { path: "rivetPeak", label: "Rivet peak", min: 0, max: 12, step: 1 },
            { path: "accentWidth", label: "Warm seam (0=off)", min: 0, max: 0.06, step: 0.002 },
            { path: "accentPeak", label: "Seam peak", min: 0, max: 12, step: 1 },
            { path: "opacity", label: "Opacity", min: 0, max: 1, step: 0.05 },
        ],
    },
    panelBay: {
        label: "Panel bays (wall face)",
        defaults: {
            type: "panelBay",
            rows: 5,
            cols: 2,
            inset: 0.16,
            frameWidth: 0.07,
            highlightPeak: 4,
            shadowPeak: 5,
            rimPeak: 5,
            interiorDarken: 5,
            surfaceMask: "wallFace",
            opacity: 0.9,
            blendMode: "add",
        },
        fields: [
            { path: "rows", label: "Rows", min: 2, max: 12, step: 1 },
            { path: "cols", label: "Cols", min: 1, max: 6, step: 1 },
            { path: "inset", label: "Bay inset", min: 0.05, max: 0.3, step: 0.01 },
            { path: "interiorDarken", label: "Interior dark", min: 0, max: 14, step: 1 },
            { path: "rimPeak", label: "Rim glow", min: 0, max: 12, step: 1 },
            { path: "opacity", label: "Opacity", min: 0, max: 1, step: 0.05 },
        ],
    },
    stainBlotch: {
        label: "Stain blotch",
        defaults: {
            type: "stainBlotch",
            coordinateSpace: "eval",
            frequency: 0.008,
            threshold: 0.55,
            peak: 5,
            offset: [0, 0],
            tint: [1, 2, 2],
            octaves: 1,
            opacity: 0.15,
            blendMode: "add",
        },
        fields: [
            { path: "frequency", label: "Frequency", min: 0.002, max: 0.05, step: 0.001 },
            { path: "threshold", label: "Threshold", min: 0, max: 0.9, step: 0.05 },
            { path: "peak", label: "Peak", min: 0, max: 20, step: 1 },
            { path: "opacity", label: "Opacity", min: 0, max: 1, step: 0.05 },
        ],
    },
    wallLighting: {
        label: "Wall lighting",
        defaults: {
            type: "wallLighting",
            power: 1,
            topDarken: 4,
            coolBias: 1.04,
            opacity: 1,
            blendMode: "multiply",
        },
        fields: [
            { path: "power", label: "Power", min: 0.2, max: 2, step: 0.05 },
            { path: "topDarken", label: "Top darken", min: 0, max: 20, step: 1 },
            { path: "coolBias", label: "Cool bias", min: 0.8, max: 1.3, step: 0.02 },
            { path: "opacity", label: "Opacity", min: 0, max: 1, step: 0.05 },
        ],
    },
    ridgeLines: {
        label: "Ridge lines",
        defaults: {
            type: "ridgeLines",
            coordinateSpace: "eval",
            frequency: 0.02,
            threshold: 0.1,
            peak: 8,
            offset: [0, 0],
            tint: [0.2, 0.8, 1.2],
            octaves: 2,
            ridged: true,
            opacity: 0.35,
            blendMode: "add",
        },
        fields: [
            { path: "frequency", label: "Frequency", min: 0.005, max: 0.06, step: 0.001 },
            { path: "threshold", label: "Threshold", min: 0, max: 0.3, step: 0.01 },
            { path: "peak", label: "Peak", min: 0, max: 20, step: 1 },
            { path: "opacity", label: "Opacity", min: 0, max: 1, step: 0.05 },
        ],
    },
    hexGrid: {
        label: "Hex grid",
        defaults: {
            type: "hexGrid",
            cellWorldSize: 16,
            groutWidth: 0.08,
            groutPeak: 12,
            groutTint: [5, 2, -3],
            cellVariation: 2,
            jitterOffset: [0, 0],
            bevelWidth: 0.0,
            highlightPeak: 8,
            shadowPeak: -6,
            bevelTint: [1, 1, 1],
            blendMode: "multiply",
            opacity: 0.9,
        },
        fields: [
            { path: "cellWorldSize", label: "Cell world px", min: 8, max: 64, step: 1 },
            { path: "groutWidth", label: "Grout width", min: 0.02, max: 0.2, step: 0.005 },
            { path: "groutPeak", label: "Grout peak", min: -20, max: 20, step: 1 },
            { path: "groutTint.0", label: "Grout R Δ", min: -12, max: 12, step: 1 },
            { path: "groutTint.1", label: "Grout G Δ", min: -12, max: 12, step: 1 },
            { path: "groutTint.2", label: "Grout B Δ", min: -12, max: 12, step: 1 },
            { path: "bevelWidth", label: "Bevel width", min: 0.0, max: 0.15, step: 0.005 },
            { path: "highlightPeak", label: "Highlight peak", min: 0, max: 20, step: 1 },
            { path: "shadowPeak", label: "Shadow peak", min: -20, max: 0, step: 1 },
            { path: "cellVariation", label: "Cell jitter", min: 0, max: 8, step: 0.5 },
            { path: "bevelCurve", label: "Bevel Curve", options: ["linear", "smooth", "steep"] },
            { path: "bevelFalloff", label: "Falloff", min: 0.1, max: 4.0, step: 0.1 },
            { path: "opacity", label: "Opacity", min: 0, max: 1, step: 0.05 },
        ],
    },
    fractalCracks: {
        label: "Fractal cracks",
        defaults: {
            type: "fractalCracks",
            coordinateSpace: "eval",
            frequency: 0.01,
            octaves: 3,
            threshold: 0.7,
            peak: 10,
            offset: [0, 0],
            tint: [1, 1, 1],
            opacity: 0.8,
            blendMode: "add",
        },
        fields: [
            { path: "frequency", label: "Frequency", min: 0.005, max: 0.05, step: 0.001 },
            { path: "octaves", label: "Octaves", min: 1, max: 6, step: 1 },
            { path: "threshold", label: "Threshold", min: 0.1, max: 0.95, step: 0.01 },
            { path: "peak", label: "Peak", min: 0, max: 20, step: 1 },
            { path: "tint.0", label: "Tint R", min: -5, max: 5, step: 0.1 },
            { path: "tint.1", label: "Tint G", min: -5, max: 5, step: 0.1 },
            { path: "tint.2", label: "Tint B", min: -5, max: 5, step: 0.1 },
            { path: "opacity", label: "Opacity", min: 0, max: 1, step: 0.05 },
        ],
    },
    circuitLattice: {
        label: "Circuit lattice",
        defaults: {
            type: "circuitLattice",
            coordinateSpace: "warped",
            frequency: 0.016,
            octaves: 2,
            angle: 0.15,
            offset: [0, 0],
            ridgeThreshold: 0.11,
            peak: 10,
            tint: [0.4, 0.5, 0.9],
            intersectionThreshold: 0.12,
            intersectionPeak: 12,
            intersectionTint: [0.5, 1.2, 1.8],
            opacity: 0.55,
            blendMode: "add",
        },
        fields: [
            { path: "frequency", label: "Frequency", min: 0.005, max: 0.04, step: 0.001 },
            { path: "angle", label: "Angle", min: 0, max: 1.57, step: 0.05 },
            { path: "ridgeThreshold", label: "Vein threshold", min: 0.05, max: 0.25, step: 0.01 },
            { path: "peak", label: "Vein peak", min: 0, max: 20, step: 1 },
            { path: "intersectionPeak", label: "Cross peak", min: 0, max: 20, step: 1 },
            { path: "opacity", label: "Opacity", min: 0, max: 1, step: 0.05 },
        ],
    },
    voronoiCell: {
        label: "Voronoi cells",
        defaults: {
            type: "voronoiCell",
            coordinateSpace: "warped",
            density: 0.035,
            edgeWidth: 0.08,
            peak: 4,
            seedSalt: 0,
            tint: [0.2, 0.4, 0.6],
            opacity: 0.12,
            blendMode: "add",
        },
        fields: [
            { path: "density", label: "Density", min: 0.01, max: 0.08, step: 0.002 },
            { path: "edgeWidth", label: "Edge width", min: 0.02, max: 0.2, step: 0.01 },
            { path: "peak", label: "Peak", min: 0, max: 16, step: 1 },
            { path: "opacity", label: "Opacity", min: 0, max: 1, step: 0.05 },
        ],
    },
    wallCircuitSnake: {
        label: "Wall circuit snake",
        defaults: {
            type: "wallCircuitSnake",
            frequency: 0.022,
            threshold: 0.22,
            peak: 12,
            tint: [1.2, 0.35, 0.1],
            wiggleAmplitude: 24,
            octaves: 2,
            opacity: 0.7,
            blendMode: "add",
        },
        fields: [
            { path: "frequency", label: "Frequency", min: 0.005, max: 0.05, step: 0.001 },
            { path: "threshold", label: "Threshold", min: 0.05, max: 0.4, step: 0.01 },
            { path: "peak", label: "Peak", min: 0, max: 20, step: 1 },
            { path: "wiggleAmplitude", label: "Wiggle", min: 0, max: 48, step: 2 },
            { path: "opacity", label: "Opacity", min: 0, max: 1, step: 0.05 },
        ],
    },
    wallHorizontalBevel: {
        label: "Wall panel ribs",
        defaults: {
            type: "wallHorizontalBevel",
            bands: 8,
            ribFill: 0.55,
            highlightPeak: 8,
            shadowPeak: 10,
            coreWidth: 0.2,
            corePeak: 6,
            coreTint: [0.4, 1.0, 1.6],
            snakeStrength: 0.25,
            opacity: 0.85,
            blendMode: "add",
        },
        fields: [
            { path: "bands", label: "Band count", min: 3, max: 16, step: 1 },
            { path: "ribFill", label: "Rib fill", min: 0.2, max: 0.9, step: 0.05 },
            { path: "highlightPeak", label: "Highlight", min: 0, max: 16, step: 1 },
            { path: "shadowPeak", label: "Shadow", min: 0, max: 16, step: 1 },
            { path: "corePeak", label: "Core glow", min: 0, max: 12, step: 1 },
            { path: "opacity", label: "Opacity", min: 0, max: 1, step: 0.05 },
        ],
    },
    panelGrid: {
        label: "Panel grid (legacy)",
        defaults: {
            type: "panelGrid",
            cellWorldSize: 16,
            groutWidth: 0.06,
            peak: 8,
            tint: [-4, -4, -3],
            variationFrequency: 0.1,
            variationAmplitude: 1,
            opacity: 0.7,
            blendMode: "multiply",
        },
        fields: [
            { path: "cellWorldSize", label: "Cell world px", min: 8, max: 64, step: 1 },
            { path: "groutWidth", label: "Grout width", min: 0.01, max: 0.2, step: 0.005 },
            { path: "peak", label: "Peak", min: 0, max: 20, step: 1 },
            { path: "opacity", label: "Opacity", min: 0, max: 1, step: 0.05 },
        ],
    },
    concentricRings: {
        label: "Concentric rings",
        defaults: {
            type: "concentricRings",
            coordinateSpace: "warped",
            frequency: 0.02,
            ringWidth: 0.08,
            peak: 10,
            offset: [0, 0],
            tint: [0.3, 0.8, 1.2],
            opacity: 0.7,
            blendMode: "add",
        },
        fields: [
            { path: "frequency", label: "Frequency", min: 0.005, max: 0.1, step: 0.001 },
            { path: "ringWidth", label: "Ring width", min: 0.01, max: 0.4, step: 0.01 },
            { path: "peak", label: "Peak", min: 0, max: 20, step: 1 },
            { path: "offset.0", label: "Center X", min: -200, max: 200, step: 5 },
            { path: "offset.1", label: "Center Y", min: -200, max: 200, step: 5 },
            { path: "tint.0", label: "Tint R", min: -5, max: 5, step: 0.1 },
            { path: "tint.1", label: "Tint G", min: -5, max: 5, step: 0.1 },
            { path: "tint.2", label: "Tint B", min: -5, max: 5, step: 0.1 },
            { path: "opacity", label: "Opacity", min: 0, max: 1, step: 0.05 },
        ],
    },
    circuitTraces: {
        label: "Circuit traces",
        defaults: {
            type: "circuitTraces",
            coordinateSpace: "warped",
            gridSize: 24,
            lineWidth: 2,
            density: 0.5,
            diagDensity: 0.15,
            peak: 10,
            tint: [0.9, 0.4, 1.1],
            padEnabled: true,
            opacity: 0.8,
            blendMode: "add",
        },
        fields: [
            { path: "gridSize", label: "Grid size", min: 8, max: 80, step: 2 },
            { path: "lineWidth", label: "Line width", min: 0.5, max: 10, step: 0.5 },
            { path: "density", label: "Density", min: 0.1, max: 0.9, step: 0.05 },
            { path: "diagDensity", label: "Diag density", min: 0.0, max: 0.8, step: 0.05 },
            { path: "peak", label: "Peak", min: 0, max: 20, step: 1 },
            { path: "tint.0", label: "Tint R", min: -5, max: 5, step: 0.1 },
            { path: "tint.1", label: "Tint G", min: -5, max: 5, step: 0.1 },
            { path: "tint.2", label: "Tint B", min: -5, max: 5, step: 0.1 },
            { path: "opacity", label: "Opacity", min: 0, max: 1, step: 0.05 },
        ],
    },
    celticWeave: {
        label: "Celtic weave",
        defaults: {
            type: "celticWeave",
            coordinateSpace: "warped",
            gridSize: 32,
            pipeWidth: 4,
            peak: 10,
            tint: [0.8, 0.9, 1.1],
            opacity: 0.8,
            blendMode: "add",
        },
        fields: [
            { path: "gridSize", label: "Grid size", min: 8, max: 64, step: 2 },
            { path: "pipeWidth", label: "Pipe width", min: 1, max: 12, step: 0.5 },
            { path: "peak", label: "Peak", min: 0, max: 20, step: 1 },
            { path: "tint.0", label: "Tint R", min: -5, max: 5, step: 0.1 },
            { path: "tint.1", label: "Tint G", min: -5, max: 5, step: 0.1 },
            { path: "tint.2", label: "Tint B", min: -5, max: 5, step: 0.1 },
            { path: "opacity", label: "Opacity", min: 0, max: 1, step: 0.05 },
        ],
    },
    topoContours: {
        label: "Topo contours",
        defaults: {
            type: "topoContours",
            coordinateSpace: "warped",
            frequency: 0.015,
            octaves: 2,
            bands: 10,
            thickness: 0.15,
            peak: 8,
            tint: [0.2, 0.7, 1.2],
            opacity: 0.6,
            blendMode: "add",
        },
        fields: [
            { path: "frequency", label: "Frequency", min: 0.005, max: 0.05, step: 0.001 },
            { path: "bands", label: "Bands", min: 1, max: 30, step: 1 },
            { path: "thickness", label: "Thickness", min: 0.01, max: 0.5, step: 0.01 },
            { path: "peak", label: "Peak", min: 0, max: 20, step: 1 },
            { path: "tint.0", label: "Tint R", min: -5, max: 5, step: 0.1 },
            { path: "tint.1", label: "Tint G", min: -5, max: 5, step: 0.1 },
            { path: "tint.2", label: "Tint B", min: -5, max: 5, step: 0.1 },
            { path: "opacity", label: "Opacity", min: 0, max: 1, step: 0.05 },
        ],
    },
    starburst: {
        label: "Starburst nodes",
        defaults: {
            type: "starburst",
            coordinateSpace: "warped",
            gridSize: 64,
            density: 0.25,
            radius: 28,
            spikes: 8,
            peak: 12,
            tint: [1.5, 0.5, 0.2],
            opacity: 0.85,
            blendMode: "add",
        },
        fields: [
            { path: "gridSize", label: "Grid size", min: 16, max: 128, step: 4 },
            { path: "density", label: "Density", min: 0.05, max: 1.0, step: 0.05 },
            { path: "radius", label: "Radius", min: 4, max: 64, step: 1 },
            { path: "spikes", label: "Spikes", min: 0, max: 20, step: 1 },
            { path: "peak", label: "Peak", min: 0, max: 20, step: 1 },
            { path: "tint.0", label: "Tint R", min: -5, max: 5, step: 0.1 },
            { path: "tint.1", label: "Tint G", min: -5, max: 5, step: 0.1 },
            { path: "tint.2", label: "Tint B", min: -5, max: 5, step: 0.1 },
            { path: "opacity", label: "Opacity", min: 0, max: 1, step: 0.05 },
        ],
    },
    circuitPanels: {
        label: "Circuit panels",
        defaults: {
            type: "circuitPanels",
            coordinateSpace: "warped",
            gridSize: 16,
            density: 0.35,
            cellVariation: 4,
            groutWidth: 0.08,
            groutPeak: -10,
            groutTint: [1, 1, 1],
            bevelWidth: 0.05,
            highlightPeak: 8,
            shadowPeak: -6,
            bevelTint: [1, 1, 1],
            sunkenDarken: 6,
            sunkenShadowPeak: -5,
            sunkenHighlightPeak: 4,
            rivetRadius: 0.12,
            rivetSpacing: 0.18,
            rivetPeak: 6,
            rivetTint: [1.5, 1.5, 2.0],
            blendMode: "add",
            opacity: 1,
        },
        fields: [
            { path: "gridSize", label: "Grid size", min: 8, max: 64, step: 1 },
            { path: "density", label: "Density", min: 0.05, max: 1.0, step: 0.05 },
            { path: "cellVariation", label: "Color jitter", min: 0, max: 12, step: 0.5 },
            { path: "groutWidth", label: "Grout width", min: 0.02, max: 0.2, step: 0.01 },
            { path: "groutPeak", label: "Grout peak", min: -20, max: 20, step: 1 },
            { path: "bevelWidth", label: "Bevel width", min: 0.01, max: 0.15, step: 0.005 },
            { path: "highlightPeak", label: "Highlight peak", min: 0, max: 20, step: 1 },
            { path: "shadowPeak", label: "Shadow peak", min: -20, max: 0, step: 1 },
            { path: "sunkenDarken", label: "Sunken darken", min: 0, max: 20, step: 0.5 },
            { path: "sunkenShadowPeak", label: "Sunken shadow", min: -20, max: 0, step: 1 },
            { path: "sunkenHighlightPeak", label: "Sunken highlight", min: 0, max: 20, step: 1 },
            { path: "rivetRadius", label: "Rivet radius", min: 0.02, max: 0.25, step: 0.01 },
            { path: "rivetSpacing", label: "Rivet spacing", min: 0.05, max: 0.35, step: 0.01 },
            { path: "rivetPeak", label: "Rivet peak", min: 0, max: 20, step: 1 },
            { path: "opacity", label: "Opacity", min: 0, max: 1, step: 0.05 },
        ],
    },
    filterHSV: {
        label: "Filter: HSV Adjust",
        defaults: { type: "filterHSV", hueShift: 0, saturation: 1, value: 1, blendMode: "replace", opacity: 1 },
        fields: [
            { path: "hueShift", label: "Hue Shift", min: -180, max: 180, step: 1 },
            { path: "saturation", label: "Saturation", min: 0, max: 5, step: 0.1 },
            { path: "value", label: "Value (Brightness)", min: 0, max: 5, step: 0.1 },
            { path: "blendMode", label: "Blend Mode", options: BLEND_OPTIONS },
            { path: "opacity", label: "Opacity", min: 0, max: 1, step: 0.05 },
        ]
    },
    filterLevels: {
        label: "Filter: Levels",
        defaults: { type: "filterLevels", blackPoint: 0, whitePoint: 255, gamma: 1.0, blendMode: "replace", opacity: 1 },
        fields: [
            { path: "blackPoint", label: "Black Point", min: 0, max: 254, step: 1 },
            { path: "whitePoint", label: "White Point", min: 1, max: 255, step: 1 },
            { path: "gamma", label: "Gamma", min: 0.1, max: 5.0, step: 0.1 },
            { path: "blendMode", label: "Blend Mode", options: BLEND_OPTIONS },
            { path: "opacity", label: "Opacity", min: 0, max: 1, step: 0.05 },
        ]
    },
    filterPosterize: {
        label: "Filter: Posterize",
        defaults: { type: "filterPosterize", bands: 4, blendMode: "replace", opacity: 1 },
        fields: [
            { path: "bands", label: "Bands", min: 2, max: 64, step: 1 },
            { path: "blendMode", label: "Blend Mode", options: BLEND_OPTIONS },
            { path: "opacity", label: "Opacity", min: 0, max: 1, step: 0.05 },
        ]
    },
    filterRGBAdjust: {
        label: "Filter: RGB Adjust",
        defaults: { type: "filterRGBAdjust", rMult: 1, gMult: 1, bMult: 1, rOffset: 0, gOffset: 0, bOffset: 0, blendMode: "replace", opacity: 1 },
        fields: [
            { path: "rMult", label: "R Multiplier", min: 0, max: 5, step: 0.1 },
            { path: "gMult", label: "G Multiplier", min: 0, max: 5, step: 0.1 },
            { path: "bMult", label: "B Multiplier", min: 0, max: 5, step: 0.1 },
            { path: "rOffset", label: "R Offset", min: -255, max: 255, step: 1 },
            { path: "gOffset", label: "G Offset", min: -255, max: 255, step: 1 },
            { path: "bOffset", label: "B Offset", min: -255, max: 255, step: 1 },
            { path: "blendMode", label: "Blend Mode", options: BLEND_OPTIONS },
            { path: "opacity", label: "Opacity", min: 0, max: 1, step: 0.05 },
        ]
    },
};

export const WARP_FIELDS = [
    { path: "warp.frequency", label: "Warp frequency", min: 0, max: 0.02, step: 0.0005 },
    { path: "warp.amplitude", label: "Warp amplitude", min: 0, max: 20, step: 1 },
    { path: "warp.octaves", label: "Warp octaves", min: 1, max: 4, step: 1 },
];

export const PALETTE_FIELDS = [
    { path: "palette.floorBase.0", label: "Floor R", min: 0, max: 64, step: 1 },
    { path: "palette.floorBase.1", label: "Floor G", min: 0, max: 64, step: 1 },
    { path: "palette.floorBase.2", label: "Floor B", min: 0, max: 64, step: 1 },
    { path: "palette.wallBase.0", label: "Wall R", min: 0, max: 64, step: 1 },
    { path: "palette.wallBase.1", label: "Wall G", min: 0, max: 64, step: 1 },
    { path: "palette.wallBase.2", label: "Wall B", min: 0, max: 64, step: 1 },
];

/** Numeric motif params that can drive profile.animation. */
export function getAnimatableMotifFields(motifConfig) {
    const schema = MOTIF_TYPES[motifConfig?.type];
    if (!schema) {
        return [];
    }
    return schema.fields.filter((field) => !field.options);
}
