export const Events = {
    UI_UPDATE: "ui:update",
    UI_UPDATE_HUD: "ui:updateHud",
    UI_SHOW_UPGRADE_CHOICE: "ui:showUpgradeChoice",
    UI_SHOW_SECTOR_CLEARED: "ui:showSectorCleared",
    UI_SHOW_NODE_CONFIRM: "ui:showNodeConfirm",
    UI_SHOW_GAME_OVER: "ui:showGameOver",
    FX_FLOATING_TEXT: "fx:floatingText",
    COMBAT_ENEMY_KILLED: "combat:enemyKilled",
    COMBAT_WAVE_CLEARED: "combat:waveCleared",
    PROGRESS_DIRTY: "progress:dirty",
    PROGRESS_SAVE: "progress:save",
    GAME_PAUSE: "game:pause",
    GAME_RESUME: "game:resume",
    GAME_TOGGLE_PAUSE: "game:togglePause",
};
