export const Events = {
    UI_UPDATE: "ui:update",
    UI_UPDATE_HUD: "ui:updateHud",
    GAME_PAUSE: "game:pause",
    GAME_RESUME: "game:resume",
    GAME_TOGGLE_PAUSE: "game:togglePause",
    GAME_SET_SPEED: "game:setSpeed",
    GAME_RESTART: "game:restart",
    RADIO_START: "radio:start",
    RADIO_TRIGGER: "radio:trigger",
    RADIO_ADVANCE: "radio:advance",
    RADIO_END: "radio:end",
    UI_SHOW_RADIO: "ui:showRadio",
    UI_HIDE_RADIO: "ui:hideRadio",
};
