export const worldPropDefinitions = {
    barrel: {
        render3DKey: "barrel",
        hitBehavior: "explosive",
        radius: 8,
        isPushable: true,
        renderMode: "3d",
        isExplosive: true,
        laserTargetable: true,
        wallPhysics: { restitution: 0.25, friction: 0.75 },
        explosion: {
            type: "standard",
            radius: 0,
            maxRadius: 100,
            speed: 300,
            damage: 100,
            lingerTimer: 750,
            fadeTimer: 250,
        },
        spawn: {
            minCount: 25,
            randomRange: 125,
            minRadius: 150,
            maxRadius: 1000,
        },
    },
    crate: {
        render3DKey: "crate",
        hitBehavior: "damage",
        radius: 8,
        isPushable: true,
        renderMode: "3d",
        laserTargetable: true,
        maxHealth: 30,
        mass: 1.5,
        wallPhysics: { restitution: 0.15, friction: 0.8 },
        spawn: {
            minCount: 8,
            randomRange: 17,
            minRadius: 150,
            maxRadius: 1000,
        },
    },
};
