const fs = require("fs");
const file = "c:/Users/mrjbl/Desktop/tower/Libraries/Navigation/NavFlowField.js";
let text = fs.readFileSync(file, "utf8");
text = text.replace(/from\s+['"]\.\/NavTopology\.js['"]/g, 'from "./NavCore.js"');
text = text.replace(/from\s+['"]\.\/NavSearch\.js['"]/g, 'from "./NavCore.js"');
text = text.replace(/from\s+['"]\.\/NavRuntime\.js['"]/g, 'from "./NavCore.js"');
text = text.replace(/from\s+['"]\.\/NavMath\.js['"]/g, 'from "./NavCore.js"');
text = text.replace(/from\s+['"]\.\/CorridorPathfinder\.js['"]/g, 'from "./NavCore.js"');
text = text.replace(/from\s+['"]\.\/NavUtils\.js['"]/g, 'from "./NavCore.js"');
text = text.replace(/from\s+['"]\.\/NavReplanPolicy\.js['"]/g, 'from "./NavCore.js"');
text = text.replace(/from\s+['"]\.\/HpaRegion\.js['"]/g, 'from "./NavHPA.js"');
text = text.replace(/from\s+['"]\.\/HpaNavigation\.js['"]/g, 'from "./NavHPA.js"');
fs.writeFileSync(file, text);
console.log("Fixed NavFlowField imports");
