import { SURFACE_PROFILE_ID } from "../procedural/profileIds.js";
/** Minimum pre-impact speed for kinetic wall chips and snake splits. */
export const SNAKE_KINETIC_MIN_STRIKE_SPEED = 28;
const SNAKE_INTENT = {
    reachSlots: {
        threat: { targetKey: "threat", mode: "flee" },
        prey: { targetKey: "prey", mode: "seek_prey" },
        food: { targetKey: "food", mode: "seek_food" },
        ally: { targetKey: "ally", mode: "seek_ally" },
    },
    committedSlots: ["prey", "food", "ally"],
    seekModes: ["seek_food", "seek_prey", "seek_ally"],
    huntMode: "seek_prey",
    fleeHeldOn: "any",
    clearMemoryOnIntentClear: false,
    filterAllyForEngagement: true,
    fleePackBlend: false,
    fleeExploreFallback: false,
    publishEngagement: true,
    decisionFields: { seekerFaction: true, seekerSegmentCount: true, session: true },
};
const FLEE_INTENT = {
    reachSlots: {
        threat: { targetKey: "threat", mode: "flee" },
        enemy: { targetKey: "prey", mode: "seek_enemy" },
        food: { targetKey: "food", mode: "seek_food" },
        ally: { targetKey: "ally", mode: "seek_ally" },
    },
    committedSlots: ["food", "enemy", "ally"],
    seekModes: ["shoot_enemy", "seek_enemy", "seek_food", "seek_ally"],
    huntMode: "seek_enemy",
    fleeHeldOn: "flee",
    clearMemoryOnIntentClear: true,
    filterAllyForEngagement: false,
    fleePackBlend: true,
    fleeExploreFallback: true,
    publishEngagement: false,
    decisionFields: {},
};
const PLAYER_FLEE_INTENT = {
    reachSlots: { enemy: { targetKey: "prey", mode: "seek_enemy" } },
    committedSlots: ["enemy"],
    seekModes: ["shoot_enemy", "seek_enemy", "explore"],
    huntMode: "seek_enemy",
    fleeHeldOn: null,
    clearMemoryOnIntentClear: true,
    filterAllyForEngagement: false,
    fleePackBlend: false,
    fleeExploreFallback: false,
    publishEngagement: false,
    decisionFields: {},
};
/** Snake autosim gameplay defaults — spacing/eat radius derived from prop radii at runtime. */
export const SNAKE_GAME_DEFAULTS = {
    bodyPressureNudgeWeight: 0.5,
    bodyPressureSpeedDamp: 2.0,
    eatMargin: 2,
    foodPickupRadius: 2,
    startRadius: 2,
    cavern: { mapSeedOffset: 11, wallHeightLevel: 1, regionPaddingCells: 4, fillChance: 0.48, iterations: 4, openBoundaryRows: 3 },
    rail: { wallHeightLevel: 1, edgeThickness: 4, corridorWidthMin: 1, corridorWidthMax: 2, extraLinkRatio: 0.25 },
    surfaceRegions: { topHalfProfileId: SURFACE_PROFILE_ID.tomatoGarden, bottomHalfProfileId: SURFACE_PROFILE_ID.poolTableFelt },
    showFocusedAgentDebug: false,
    focusedAgentDebug: { agentSlots: {}, pathPreview: { cellCount: 3 }, targetRing: {} },
    aiBudget: { thinkPerFrame: 32, focusedThinkEveryFrame: true, onScreenThinkInterval: 1, offScreenThinkInterval: 4, dormantThinkInterval: 30 },
    agentCallouts: {
        enabled: true,
        profileIds: ["flee_agent"],
        agentCooldownMs: 3200,
        maxPerSecond: 3,
        preferOnScreen: true,
        color: "#f1c40f",
        duration: 1200,
        yOffset: -14,
        topicCooldownMs: { enemy_spotted: 5000, engaging: 4500, following: 6500, getting_food: 5000, falling_back: 4500 },
        topics: {
            enemy_spotted: { priority: 90, phrases: ["enemy spotted!", "contact!", "hostiles!"] },
            engaging: { priority: 80, phrases: ["engaging!", "opening fire!", "fire!"] },
            falling_back: { priority: 70, phrases: ["falling back!", "oh crap!", "nope!", "retreat!", "get out!"] },
            getting_food: { priority: 40, phrases: ["getting food!", "need food!", "snack run!"] },
            following: { priority: 30, phrases: ["following!", "got your back!", "with you!"] },
        },
    },
    splitImpulseThreshold: 35,
    kineticMinStrikeSpeed: SNAKE_KINETIC_MIN_STRIKE_SPEED,
    wallDamage: { minBreakStrength: 0.1, referenceMaxSpeed: 560 },
    shared: {
        visionRange: { range: 128 },
        decisionReachHorizon: 32,
        exploreMinTiles: 8,
        exploreFallbackMinTiles: 1,
        spatialMemoryCapacity: 128,
        navMemoryStepPenalty: 6,
        navMemoryStepFalloff: 0.65,
        fleeTiles: 8,
        fleeRange: null,
        lethalThreatRange: 48,
        fleeHysteresis: { minTicks: 45, exitThreatSeverity: 0.15, refreshAtSeverity: 0.35 },
        targetingHysteresis: { targetStickyFactor: 0.75 },
        intentMemory: { threatTtlTicks: 45, preyTtlTicks: 90, foodTtlTicks: 180, allyTtlTicks: 60, engagedPreyTtlTicks: 270, engagedThreatTtlTicks: 180 },
        terminalHoming: { enabled: true, handoffRadius: null, requireWorldLos: true, minHoldTicks: 6 },
    },
    agentProfiles: {
        snake: {
            exportType: "snake",
            topology: "chain",
            populationCount: 32,
            bodyPropId: "ball",
            headPropId: "snake_head",
            segmentCount: 3,
            leaderIndex: 0,
            teams: [
                { faction: "red", color: "#e74c3c" },
                { faction: "blue", color: "#3498db" },
                { faction: "purple", color: "#9b59b6" },
            ],
            linkSlack: 1.0,
            growDirX: -1,
            growDirY: 0,
            minAliveSegmentCount: 3,
            maxAliveSegmentCount: 8,
            metabolism: { hungerDrainMs: 30_000, foodValue: 0.5, growthCost: 1.0, starveShedIntervalMs: 10_000 },
            rivalBand: { maxSegmentGap: 2 },
            combat: { topology: "chain", canSplit: true, victimOfFleeEscapeRam: true, victimOfHeadStrikeRam: true, preyHeadRamImmuneLeader: true },
            relationships: { snake: { type: "sizeBand", sameFaction: "ally" }, flee_agent: "prey", player_flee: "prey" },
            species: { retireNavOnDeath: true, pressureDiagnostics: true },
            gameplay: { leader: { maxSpeed: 250, accel: 200, friction: 2.0 }, body: { friction: 2.25, density: 0.001 } },
            scoringEnv: { effortFallback: true },
            hungerBands: [
                { id: "satisfied", min: 0.66 },
                { id: "hungry", min: 0.33 },
                { id: "desperate", min: 0 },
            ],
            decisionWeights: { flee: 400, prey: 300, food: 340, seek_ally: 120, explore: 240 },
            factionCohesion: { arrivalRadius: 32, idealStopDist: 3, packBonus: 5, satisfiedBonus: 50, referenceSegmentCount: 3, maxSegmentScale: 10 },
            decisionPressure: {
                foodHungerBonus: 300,
                preyDesperationBonus: 250,
                enemySnakePreyValue: 1300,
                riskTolerance: { satisfied: 0, hungry: 0.4, desperate: 0.75 },
                effort: { costPerCell: { satisfied: 25, hungry: 20, desperate: 6 }, preyValue: { satisfied: 140, hungry: 300, desperate: 550 } },
            },
            sprint: {
                fleeSeverity: 0.5,
                speedMultiplier: 1.4,
                accelMultiplier: 1.4,
                hungerDrainMultiplier: 2.5,
                rules: [
                    { mode: "flee", rule: "severeOrLethalThreat", want: true, reason: "escape" },
                    { mode: "seek_food", rule: "severeNonLethalThreat", want: true, reason: "feed" },
                    { mode: "seek_prey", rule: "always", want: true, reason: "chase" },
                ],
            },
            decision: {
                scoreOrder: ["flee", "seek_prey", "seek_food", "seek_ally", "explore"],
                targetLost: { seek_prey: "prey", seek_food: "food", seek_ally: "ally" },
                remembered: [{ key: "threat" }, { key: "prey" }, { key: "food" }, { key: "ally" }, { key: "allyCount", allyCount: 1 }, { key: "allyCentroid", constant: null }],
                eventTargets: ["threat", "prey", "food", "ally"],
                slots: { threat: {}, prey: {}, food: {}, ally: { known: "engagedAlly" } },
                fields: {
                    allyCount: {
                        visible: { from: "allyCount", default: 0 },
                        known: { anchorSlot: "ally", matchWorldSlot: "ally", fromVisible: "allyCount", fromRemembered: "allyCount", whenMissing: 0 },
                    },
                    allyCentroid: {
                        visible: { from: "allyCentroid", default: null },
                        known: { anchorSlot: "ally", matchWorldSlot: "ally", fromVisible: "allyCentroid", whenMissing: null, whenNoMatch: null },
                    },
                },
                modes: {
                    flee: { scorer: "riskAdjustedFlee" },
                    seek_prey: { scorer: "preyWithEffort", slot: "prey" },
                    seek_food: { scorer: "foodWithHunger", slot: "food" },
                    seek_ally: { scorer: "regroupAlly", slot: "ally", cohesion: "snake", guards: ["requiresLeadworthy", "requiresSatisfied", "noThreat", "allyCloseEnough"] },
                    explore: { scorer: "constant", weightKey: "explore" },
                },
            },
            visibleSources: { food: { category: "food", accept: "edibleFood" } },
            intent: SNAKE_INTENT,
        },
        flee_agent: {
            exportType: "flee_agent",
            topology: "single",
            useFactionTint: true,
            populationCount: 512,
            spawnSeedOffset: 9173,
            bodyPropId: "boid_triangle",
            segmentCount: 1,
            leaderIndex: 0,
            faction: "bravo",
            attackRange: 48,
            weapon: {
                maxRangeVisionInset: 16,
                reactionMs: 150,
                fireDelayMs: 150,
                magazineSize: 3,
                reloadMs: 500,
                fireAimToleranceRad: 0.08,
                bulletSpeed: 160,
                spawnDist: 4.5,
                aimRotationRadPerSec: 4.71238898038469,
                combatMovement: { strafeTiles: 3, repickTicks: 45, idealRangeFraction: 0.65, rangeBandCells: 2, speedFraction: 0.5, accelFraction: 0.6, orbitBias: 60 },
            },
            combat: { topology: "ball", fleeBallHeadRam: true, fleeEscapeRam: true },
            relationships: { snake: { type: "proximity", near: "threat", far: "prey", range: 48 }, flee_agent: { type: "faction", same: "ally", different: "prey" }, player_flee: "prey" },
            species: {},
            gameplay: { leader: { maxSpeed: 100, accel: 200 } },
            teams: [
                { faction: "charlie", color: "#f1c40f" },
                { faction: "delta", color: "#2ecc71" },
                { faction: "echo", color: "#e67e22" },
            ],
            initialHunger: 0.85,
            metabolism: { hungerDrainMs: 90_000, foodValue: 0.35 },
            scoringEnv: { sprint: true },
            hungerBands: [
                { id: "satisfied", min: 0.66 },
                { id: "hungry", min: 0.33 },
                { id: "desperate", min: 0 },
            ],
            sprint: {
                fleeSeverity: 0.5,
                speedMultiplier: 1.75,
                accelMultiplier: 1.5,
                hungerDrainMultiplier: 2.0,
                sprintFleeMinHunger: 0.1,
                rules: [
                    { mode: "flee", rule: "severeOrLethalThreat", guards: ["minHunger"], want: true, reason: "escape" },
                    { mode: "seek_food", rule: "severeNonLethalThreat", guards: ["minHunger", "bandDesperate"], want: true, reason: "race" },
                    { mode: "seek_enemy", rule: "always", want: true, reason: "attack" },
                ],
            },
            decisionWeights: { flee: 400, shoot_enemy: 460, enemy: 420, food: 360, seek_ally: 140, explore: 260 },
            factionCohesion: { arrivalRadius: 48, idealStopDist: 2.5, packBonus: 8, satisfiedBonus: 60, fleePackBlend: 0.35, maxPackDistCells: 16 },
            decisionPressure: {
                foodHungerBonus: 280,
                sprintFleeMinHunger: 0.1,
                outnumberedFleeBonus: 0.4,
                sprintFoodCostPenalty: 40,
                riskTolerance: { satisfied: 0, hungry: 0.35, desperate: 0.65 },
                effort: { costPerCell: { satisfied: 22, hungry: 18, desperate: 8 } },
            },
            targetingHysteresis: { targetStickyFactor: 0.3 },
            decision: {
                scoreOrder: ["flee", "shoot_enemy", "seek_enemy", "seek_food", "seek_ally", "explore"],
                targetLost: { shoot_enemy: "enemy", seek_enemy: "enemy", seek_food: "food", seek_ally: "ally" },
                remembered: [{ key: "threat" }, { key: "enemy", memoryKey: "prey" }, { key: "food" }, { key: "ally" }, { key: "allyCount", allyCount: 1 }, { key: "allyCentroid", constant: null }],
                eventTargets: ["threat", "food", "enemy", "ally"],
                slots: { threat: {}, enemy: { visibleFrom: "prey", memoryKey: "prey", hideVisibleWhenMemory: true, known: "visibleOrRemembered" }, food: {}, ally: { hideVisibleWhenMemory: true } },
                fields: {
                    threatCount: { visible: { from: "threatCount", default: 0 }, known: { fromVisible: "threatCount", default: 0 } },
                    allyCount: {
                        visible: { from: "allyCount", default: 0, ifMemory: { key: "ally", use: 0 } },
                        known: { visibleIfSlot: "ally", fromVisible: "allyCount", fromRemembered: "allyCount" },
                    },
                    allyCentroid: { visible: { from: "allyCentroid", default: null, ifMemory: { key: "ally", use: null } }, known: { fromVisible: "allyCentroid" } },
                },
                modes: {
                    flee: { scorer: "riskAdjustedFlee", mods: ["outnumberedFlee"] },
                    shoot_enemy: { scorer: "rangedAttack", slot: "enemy", weightKey: "shoot_enemy", guards: ["noThreat"] },
                    seek_enemy: { scorer: "reachTarget", slot: "enemy", weightKey: "enemy", guards: ["noThreat", "canShootEnemy", "rangedEnemyTooClose"] },
                    seek_food: { scorer: "foodWithHunger", slot: "food", guards: ["notSatisfied"] },
                    seek_ally: { scorer: "regroupAlly", slot: "ally", cohesion: "flee", guards: ["noThreat", "notDesperate", "allyCloseEnough"] },
                    explore: { scorer: "constant", weightKey: "explore" },
                },
            },
            visibleSources: { food: { category: "food", accept: "edibleFood" } },
            intent: FLEE_INTENT,
        },
        player_flee: {
            exportType: "player_flee",
            topology: "single",
            useFactionTint: true,
            populationCount: 1,
            spawnSeedOffset: 9876,
            bodyPropId: "player_flee",
            segmentCount: 1,
            leaderIndex: 0,
            faction: "player_flee",
            attackRange: 48,
            weapon: {
                maxRangeVisionInset: 16,
                reactionMs: 150,
                fireDelayMs: 150,
                magazineSize: 3,
                reloadMs: 500,
                fireAimToleranceRad: 0.08,
                bulletSpeed: 160,
                spawnDist: 4.5,
                aimRotationRadPerSec: 4.71238898038469,
                combatMovement: { strafeTiles: 3, repickTicks: 45, idealRangeFraction: 0.65, rangeBandCells: 2, speedFraction: 0.5, accelFraction: 0.6, orbitBias: 60 },
            },
            combat: { topology: "ball", fleeBallHeadRam: true, fleeEscapeRam: true },
            relationships: { snake: "prey", flee_agent: "prey" },
            species: {},
            gameplay: { leader: { maxSpeed: 100, accel: 200 } },
            teams: [{ faction: "player_flee", color: "#808080" }],
            initialHunger: 0.85,
            metabolism: { hungerDrainMs: 90_000, foodValue: 0.35 },
            autonomous: false,
            decisionWeights: { explore: 100, shoot_enemy: 460, enemy: 420 },
            decisionPressure: {
                foodHungerBonus: 280,
                sprintFleeMinHunger: 0.1,
                outnumberedFleeBonus: 0.4,
                sprintFoodCostPenalty: 40,
                riskTolerance: { satisfied: 0, hungry: 0.35, desperate: 0.65 },
                effort: { costPerCell: { satisfied: 22, hungry: 18, desperate: 8 } },
            },
            decision: {
                scoreOrder: ["explore", "shoot_enemy", "seek_enemy"],
                targetLost: { shoot_enemy: "enemy", seek_enemy: "enemy" },
                remembered: [{ key: "threat" }, { key: "enemy", memoryKey: "prey" }],
                eventTargets: ["threat", "enemy"],
                slots: { threat: {}, enemy: { visibleFrom: "prey", memoryKey: "prey", hideVisibleWhenMemory: true, known: "visibleOrRemembered" } },
                fields: {},
                modes: {
                    shoot_enemy: { scorer: "rangedAttack", slot: "enemy", weightKey: "shoot_enemy", guards: ["noThreat"] },
                    seek_enemy: { scorer: "reachTarget", slot: "enemy", weightKey: "enemy", guards: ["noThreat", "canShootEnemy", "rangedEnemyTooClose"] },
                    explore: { scorer: "constant", weightKey: "explore" },
                },
            },
            intent: PLAYER_FLEE_INTENT,
        },
    },
};
