/** Minimum pre-impact speed for kinetic wall chips and snake splits. */
export const SNAKE_KINETIC_MIN_STRIKE_SPEED = 28;
const SNAKE_INTENT = {
    reachSlots: {
        threat: { targetKey: "threat", mode: "flee" },
        prey: { targetKey: "prey", mode: "seek_prey" },
        food: { targetKey: "food", mode: "seek_food" },
        ally: { targetKey: "ally", mode: "seek_ally" },
    },
    committedSlots: ["prey", "food", "ally"],
    seekModes: ["seek_food", "seek_prey", "seek_ally"],
    huntMode: "seek_prey",
    fleeHeldOn: "any",
    clearMemoryOnIntentClear: false,
    filterAllyForEngagement: true,
    fleePackBlend: false,
    fleeExploreFallback: false,
    publishEngagement: true,
    returnShape: "fsmSnapshot",
    decisionFields: { seekerFaction: true, seekerSegmentCount: true, session: true },
};
const SQUID_INTENT = {
    reachSlots: { threat: { targetKey: "threat", mode: "flee" }, prey: { targetKey: "prey", mode: "seek_prey" }, food: { targetKey: "food", mode: "seek_food" } },
    committedSlots: ["prey", "food"],
    seekModes: ["seek_food", "seek_prey"],
    huntMode: "seek_prey",
    fleeHeldOn: "any",
    clearMemoryOnIntentClear: false,
    filterAllyForEngagement: false,
    fleePackBlend: false,
    fleeExploreFallback: false,
    publishEngagement: false,
    returnShape: "fsmSnapshot",
    decisionFields: { seekerFaction: true, seekerSegmentCount: true },
};
const FLEE_INTENT = {
    reachSlots: {
        threat: { targetKey: "threat", mode: "flee" },
        enemy: { targetKey: "prey", mode: "seek_enemy" },
        food: { targetKey: "food", mode: "seek_food" },
        ally: { targetKey: "ally", mode: "seek_ally" },
    },
    committedSlots: ["food", "enemy", "ally"],
    seekModes: ["shoot_enemy", "seek_enemy", "seek_food", "seek_ally"],
    huntMode: "seek_enemy",
    fleeHeldOn: "flee",
    clearMemoryOnIntentClear: true,
    filterAllyForEngagement: false,
    fleePackBlend: true,
    fleeExploreFallback: true,
    publishEngagement: false,
    decisionFields: {},
};
/** Snake autosim gameplay defaults — spacing/eat radius derived from prop radii at runtime. */
export const SNAKE_GAME_DEFAULTS = {
    bodyPressureNudgeWeight: 0.5,
    bodyPressureSpeedDamp: 2.0,
    eatMargin: 2,
    foodPickupRadius: 2,
    startRadius: 2,
    cavern: { mapSeedOffset: 11, wallHeightLevel: 1, regionPaddingCells: 4, fillChance: 0.48, iterations: 4, openBoundaryRows: 3 },
    rail: { wallHeightLevel: 1, edgeThickness: 4, corridorWidthMin: 1, corridorWidthMax: 2, extraLinkRatio: 0.25 },
    showFocusedAgentDebug: false,
    focusedAgentDebug: { agentSlots: {}, pathPreview: { cellCount: 3 }, targetRing: {} },
    aiBudget: { thinkPerFrame: 32, focusedThinkEveryFrame: true, onScreenThinkInterval: 1, offScreenThinkInterval: 4, dormantThinkInterval: 30 },
    splitImpulseThreshold: 35,
    kineticMinStrikeSpeed: SNAKE_KINETIC_MIN_STRIKE_SPEED,
    wallDamage: { maxHp: 100, maxHitDamage: 45, minAngleFactor: 0.2, referenceMaxSpeed: 560 },
    shared: {
        visionRange: { range: 128 },
        decisionReachHorizon: 32,
        exploreMinTiles: 8,
        exploreFallbackMinTiles: 1,
        spatialMemoryCapacity: 128,
        navMemoryStepPenalty: 6,
        navMemoryStepFalloff: 0.65,
        fleeTiles: 8,
        fleeRange: null,
        lethalThreatRange: 48,
        fleeHysteresis: { minTicks: 45, exitThreatSeverity: 0.15, refreshAtSeverity: 0.35 },
        targetingHysteresis: { targetStickyFactor: 0.75 },
        intentMemory: { threatTtlTicks: 45, preyTtlTicks: 90, foodTtlTicks: 180, allyTtlTicks: 60 },
        terminalHoming: { enabled: true, handoffRadius: null, requireWorldLos: true, minHoldTicks: 6 },
    },
    agentProfiles: {
        snake: {
            exportType: "snake",
            populationCount: 160,
            bodyPropId: "ball",
            headPropId: "snake_head",
            segmentCount: 3,
            leaderIndex: 0,
            linkSlack: 1.0,
            growDirX: -1,
            growDirY: 0,
            minAliveSegmentCount: 3,
            maxAliveSegmentCount: 8,
            metabolism: { hungerDrainMs: 30_000, foodValue: 0.5, growthCost: 1.0, starveShedIntervalMs: 10_000 },
            rivalBand: { maxSegmentGap: 2 },
            combat: { topology: "chain", canSplit: true, victimOfFleeEscapeRam: true, victimOfHeadStrikeRam: true, preyHeadRamImmuneLeader: true },
            relationships: { snake: { type: "sizeBand", sameFaction: "ally" }, flee_agent: "prey", squid: "threat" },
            species: { retireNavOnDeath: true, pressureDiagnostics: true },
            gameplay: { leader: { maxSpeed: 250, accel: 200, friction: 2.0 }, body: { friction: 2.25, density: 0.001 } },
            scoringEnv: { effortFallback: true },
            hungerBands: [
                { id: "satisfied", min: 0.66 },
                { id: "hungry", min: 0.33 },
                { id: "desperate", min: 0 },
            ],
            decisionWeights: { flee: 400, prey: 300, food: 340, seek_ally: 220, explore: 100 },
            factionCohesion: { arrivalRadius: 32, idealStopDist: 3, packBonus: 15, satisfiedBonus: 50, referenceSegmentCount: 3, maxSegmentScale: 10 },
            decisionPressure: {
                foodHungerBonus: 300,
                preyDesperationBonus: 250,
                enemySnakePreyValue: 1300,
                riskTolerance: { satisfied: 0, hungry: 0.4, desperate: 0.75 },
                effort: { costPerCell: { satisfied: 25, hungry: 20, desperate: 6 }, preyValue: { satisfied: 140, hungry: 300, desperate: 550 } },
            },
            sprint: {
                fleeSeverity: 0.5,
                speedMultiplier: 1.4,
                accelMultiplier: 1.4,
                hungerDrainMultiplier: 2.5,
                rules: [
                    { mode: "flee", rule: "severeOrLethalThreat", want: true, reason: "escape" },
                    { mode: "seek_food", rule: "severeNonLethalThreat", want: true, reason: "feed" },
                    { mode: "seek_prey", rule: "always", want: true, reason: "chase" },
                ],
            },
            decision: {
                scoreOrder: ["flee", "seek_prey", "seek_food", "seek_ally", "explore"],
                targetLost: { seek_prey: "prey", seek_food: "food", seek_ally: "ally" },
                remembered: [{ key: "threat" }, { key: "prey" }, { key: "food" }, { key: "ally" }, { key: "allyCount", allyCount: 1 }, { key: "allyCentroid", constant: null }],
                eventTargets: ["threat", "prey", "food", "ally"],
                slots: { threat: {}, prey: {}, food: {}, ally: { known: "engagedAlly" } },
                fields: {
                    allyCount: {
                        visible: { from: "allyCount", default: 0 },
                        known: { anchorSlot: "ally", matchWorldSlot: "ally", fromVisible: "allyCount", fromRemembered: "allyCount", whenMissing: 0 },
                    },
                    allyCentroid: {
                        visible: { from: "allyCentroid", default: null },
                        known: { anchorSlot: "ally", matchWorldSlot: "ally", fromVisible: "allyCentroid", whenMissing: null, whenNoMatch: null },
                    },
                },
                modes: {
                    flee: { scorer: "riskAdjustedFlee" },
                    seek_prey: { scorer: "preyWithEffort", slot: "prey" },
                    seek_food: { scorer: "foodWithHunger", slot: "food" },
                    seek_ally: { scorer: "regroupAlly", slot: "ally", cohesion: "snake", guards: ["requiresLeadworthy", "requiresSatisfied", "noThreat"] },
                    explore: { scorer: "constant", weightKey: "explore" },
                },
            },
            visibleSources: { food: { category: "food", accept: "edibleFood" } },
            intent: SNAKE_INTENT,
        },
        flee_agent: {
            exportType: "flee_agent",
            populationCount: 128,
            spawnSeedOffset: 9173,
            bodyPropId: "boid_triangle",
            segmentCount: 1,
            leaderIndex: 0,
            faction: "bravo",
            attackRange: 48,
            weapon: { maxRange: 128, reactionMs: 150, fireDelayMs: 150, magazineSize: 3, reloadMs: 500, bulletSpeed: 500, spawnDist: 4.5, aimRotationRadPerSec: 4.71238898038469 },
            combat: { topology: "ball", fleeBallHeadRam: true, fleeEscapeRam: true },
            relationships: { snake: { type: "proximity", near: "threat", far: "prey", range: 48 }, squid: "threat", flee_agent: { type: "faction", same: "ally", different: "prey" } },
            species: {},
            gameplay: { leader: { maxSpeed: 100, accel: 200 } },
            teams: [
                { faction: "charlie", color: "#f1c40f" },
                { faction: "delta", color: "#2ecc71" },
                { faction: "echo", color: "#e67e22" },
            ],
            initialHunger: 0.85,
            metabolism: { hungerDrainMs: 90_000, foodValue: 0.35 },
            scoringEnv: { sprint: true },
            hungerBands: [
                { id: "satisfied", min: 0.66 },
                { id: "hungry", min: 0.33 },
                { id: "desperate", min: 0 },
            ],
            sprint: {
                fleeSeverity: 0.5,
                speedMultiplier: 1.75,
                accelMultiplier: 1.5,
                hungerDrainMultiplier: 2.0,
                sprintFleeMinHunger: 0.1,
                rules: [
                    { mode: "flee", rule: "severeOrLethalThreat", guards: ["minHunger"], want: true, reason: "escape" },
                    { mode: "seek_food", rule: "severeNonLethalThreat", guards: ["minHunger", "bandDesperate"], want: true, reason: "race" },
                    { mode: "shoot_enemy", rule: "always", want: true, reason: "attack" },
                    { mode: "seek_enemy", rule: "always", want: true, reason: "attack" },
                ],
            },
            decisionWeights: { flee: 400, shoot_enemy: 460, enemy: 420, food: 360, seek_ally: 280, explore: 100 },
            factionCohesion: { arrivalRadius: 24, idealStopDist: 2.5, packBonus: 20, satisfiedBonus: 60, fleePackBlend: 0.35, maxPackDistCells: 16 },
            decisionPressure: {
                foodHungerBonus: 280,
                sprintFleeMinHunger: 0.1,
                outnumberedFleeBonus: 0.4,
                sprintFoodCostPenalty: 40,
                riskTolerance: { satisfied: 0, hungry: 0.35, desperate: 0.65 },
                effort: { costPerCell: { satisfied: 22, hungry: 18, desperate: 8 } },
            },
            decision: {
                scoreOrder: ["flee", "shoot_enemy", "seek_enemy", "seek_food", "seek_ally", "explore"],
                targetLost: { shoot_enemy: "enemy", seek_enemy: "enemy", seek_food: "food", seek_ally: "ally" },
                remembered: [{ key: "threat" }, { key: "enemy", memoryKey: "prey" }, { key: "food" }, { key: "ally" }, { key: "allyCount", allyCount: 1 }, { key: "allyCentroid", constant: null }],
                eventTargets: ["threat", "food", "enemy", "ally"],
                slots: { threat: {}, enemy: { visibleFrom: "prey", memoryKey: "prey", hideVisibleWhenMemory: true, known: "visibleOrRemembered" }, food: {}, ally: { hideVisibleWhenMemory: true } },
                fields: {
                    threatCount: { visible: { from: "threatCount", default: 0 }, known: { fromVisible: "threatCount", default: 0 } },
                    allyCount: {
                        visible: { from: "allyCount", default: 0, ifMemory: { key: "ally", use: 0 } },
                        known: { visibleIfSlot: "ally", fromVisible: "allyCount", fromRemembered: "allyCount" },
                    },
                    allyCentroid: { visible: { from: "allyCentroid", default: null, ifMemory: { key: "ally", use: null } }, known: { fromVisible: "allyCentroid" } },
                },
                modes: {
                    flee: { scorer: "riskAdjustedFlee", mods: ["outnumberedFlee"] },
                    shoot_enemy: { scorer: "rangedAttack", slot: "enemy", weightKey: "shoot_enemy", guards: ["noThreat"] },
                    seek_enemy: { scorer: "reachTarget", slot: "enemy", weightKey: "enemy", guards: ["noThreat", "canShootEnemy", "rangedEnemyTooClose"] },
                    seek_food: { scorer: "foodWithHunger", slot: "food", guards: ["notSatisfied"] },
                    seek_ally: { scorer: "regroupAlly", slot: "ally", cohesion: "flee", guards: ["noThreat", "notDesperate"] },
                    explore: { scorer: "constant", weightKey: "explore" },
                },
            },
            visibleSources: { food: { category: "food", accept: "edibleFood" } },
            intent: FLEE_INTENT,
        },
        squid: {
            exportType: "squid",
            populationCount: 1,
            spawnSeedOffset: 37,
            spawnSeedIgnoreMapSeedOffset: true,
            teams: [
                { faction: "charlie", color: "#9b59b6" },
                { faction: "delta", color: "#1abc9c" },
            ],
            bodyPropId: "ball",
            brainPropId: "snake_head",
            segmentCount: 3,
            leaderIndex: 1,
            armSegmentCount: 1,
            attackRange: 48,
            combat: { topology: "chain", brainRamResolver: "squidVsSquid", preyHeadRamImmuneNonLeader: true },
            relationships: {
                flee_agent: { type: "proximity", near: "prey", far: "neutral" },
                snake: { type: "proximity", near: "prey", far: "neutral" },
                squid: { type: "proximity", near: "prey", far: "threat" },
            },
            species: { fracturableBeforeShatter: true, removeNonStruckSegments: true },
            gameplay: { leader: { maxSpeed: 180, accel: 160, friction: 2.25 }, body: { friction: 2.5, density: 0.001 } },
            linkSlack: 1.0,
            growDirX: -1,
            growDirY: 0,
            minAliveSegmentCount: 2,
            metabolism: { hungerDrainMs: 15_000, foodValue: 0.5 },
            rivalBand: { maxSegmentGap: 2 },
            scoringEnv: { effortFallback: true },
            hungerBands: [
                { id: "satisfied", min: 0.66 },
                { id: "hungry", min: 0.33 },
                { id: "desperate", min: 0 },
            ],
            decisionWeights: { flee: 360, prey: 400, food: 320, explore: 100 },
            factionCohesion: { referenceSegmentCount: 3 },
            decisionPressure: {
                foodHungerBonus: 320,
                preyDesperationBonus: 280,
                enemySnakePreyValue: 1200,
                riskTolerance: { satisfied: 0.1, hungry: 0.45, desperate: 0.8 },
                effort: { costPerCell: { satisfied: 28, hungry: 22, desperate: 8 }, preyValue: { satisfied: 160, hungry: 320, desperate: 580 } },
            },
            sprint: {
                fleeSeverity: 0.5,
                speedMultiplier: 1.35,
                accelMultiplier: 1.35,
                hungerDrainMultiplier: 2.2,
                rules: [
                    { mode: "flee", rule: "severeOrLethalThreat", want: true, reason: "escape" },
                    { mode: "seek_food", rule: "severeNonLethalThreat", want: true, reason: "feed" },
                    { mode: "seek_prey", rule: "always", want: true, reason: "attack" },
                ],
            },
            decision: {
                scoreOrder: ["flee", "seek_prey", "seek_food", "explore"],
                targetLost: { seek_prey: "prey", seek_food: "food" },
                remembered: [{ key: "threat" }, { key: "prey" }, { key: "food" }],
                eventTargets: ["threat", "prey", "food"],
                slots: { threat: {}, prey: {}, food: {} },
                fields: {},
                modes: {
                    flee: { scorer: "riskAdjustedFlee" },
                    seek_prey: { scorer: "preyWithEffort", slot: "prey", guards: ["preyTooFar"], maxPreyReach: 3 },
                    seek_food: { scorer: "foodWithHunger", slot: "food" },
                    explore: { scorer: "constant", weightKey: "explore" },
                },
            },
            visibleSources: { food: { category: "food", accept: "edibleFood" } },
            intent: SQUID_INTENT,
        },
    },
};
