/** Minimum pre-impact speed for kinetic wall chips and snake splits. */
export const SNAKE_KINETIC_MIN_STRIKE_SPEED = 28;
const SNAKE_INTENT = {
    reachSlots: {
        threat: { targetKey: "threat", mode: "flee" },
        prey: { targetKey: "prey", mode: "seek_prey" },
        food: { targetKey: "food", mode: "seek_food" },
        ally: { targetKey: "ally", mode: "seek_ally" },
    },
    committedSlots: ["prey", "food", "ally"],
    seekModes: ["seek_food", "seek_prey", "seek_ally"],
    huntMode: "seek_prey",
    perceiveSource: "visible",
    fleeHeldOn: "any",
    clearMemoryOnIntentClear: false,
    filterAllyForEngagement: true,
    fleePackBlend: false,
    fleeExploreFallback: false,
    publishEngagement: true,
    returnShape: "fsmSnapshot",
    attachDecisionToPerceiveWorld: false,
    decisionFields: { seekerFaction: true, seekerSegmentCount: true, session: true },
};
const SQUID_INTENT = {
    reachSlots: { threat: { targetKey: "threat", mode: "flee" }, prey: { targetKey: "prey", mode: "seek_prey" }, food: { targetKey: "food", mode: "seek_food" } },
    committedSlots: ["prey", "food"],
    seekModes: ["seek_food", "seek_prey"],
    huntMode: "seek_prey",
    perceiveSource: "visible",
    fleeHeldOn: "any",
    clearMemoryOnIntentClear: false,
    filterAllyForEngagement: false,
    fleePackBlend: false,
    fleeExploreFallback: false,
    publishEngagement: false,
    returnShape: "fsmSnapshot",
    attachDecisionToPerceiveWorld: false,
    decisionFields: { seekerFaction: true, seekerSegmentCount: true },
};
const FLEE_INTENT = {
    reachSlots: {
        threat: { targetKey: "threat", mode: "flee" },
        enemy: { targetKey: "prey", mode: "seek_enemy" },
        food: { targetKey: "food", mode: "seek_food" },
        ally: { targetKey: "ally", mode: "seek_ally" },
    },
    committedSlots: ["food", "enemy", "ally"],
    seekModes: ["seek_enemy", "seek_food", "seek_ally"],
    huntMode: "seek_enemy",
    perceiveSource: "memory",
    fleeHeldOn: "flee",
    clearMemoryOnIntentClear: true,
    filterAllyForEngagement: false,
    fleePackBlend: true,
    fleeExploreFallback: true,
    publishEngagement: false,
    returnShape: "intentTick",
    attachDecisionToPerceiveWorld: true,
    decisionFields: {},
};
/** Snake autosim gameplay defaults — spacing/eat radius derived from prop radii at runtime. */
export const SNAKE_GAME_DEFAULTS = {
    snakeCount: 64,
    boidCount: 128,
    squidCount: 32,
    bodyPressureNudgeWeight: 0.5,
    bodyPressureSpeedDamp: 2.0,
    eatMargin: 2,
    foodPickupRadius: 2,
    startRadius: 2,
    cavern: { mapSeedOffset: 11, wallHeightLevel: 1, regionPaddingCells: 4, fillChance: 0.48, iterations: 4, openBoundaryRows: 3 },
    rail: { wallHeightLevel: 1, edgeThickness: 4, corridorWidthMin: 1, corridorWidthMax: 2, extraLinkRatio: 0.25 },
    showFocusedAgentDebug: false,
    focusedAgentDebug: { vision: true, spatialMemory: true, path: true, agentSlots: {}, pathPreview: { cellCount: 3 }, targetRing: {} },
    showMemoryHeatmap: false,
    memoryHeatmap: { bucketCount: 8, fillRgb: "180, 100, 255", fillAlphaMax: 0.12, fillAlphaMin: 0.02 },
    brainSyncOffScreenInterval: 4,
    splitImpulseThreshold: 35,
    kineticMinStrikeSpeed: SNAKE_KINETIC_MIN_STRIKE_SPEED,
    wallDamage: { maxHp: 100, maxHitDamage: 45, minAngleFactor: 0.2, referenceMaxSpeed: 560 },
    shared: {
        visionRange: { range: 128, cellFill: "rgba(120, 220, 255, 0.04)", visibleGoalStroke: "rgba(255, 220, 80, 0.35)", lineWidth: 1 },
        decisionReachHorizon: 32,
        exploreMinTiles: 8,
        exploreFallbackMinTiles: 1,
        spatialMemoryCapacity: 128,
        navMemoryStepPenalty: 6,
        navMemoryStepFalloff: 0.65,
        fleeTiles: 8,
        fleeRange: null,
        lethalThreatRange: 48,
        fleeHysteresis: { minTicks: 45, exitThreatSeverity: 0.15, refreshAtSeverity: 0.35 },
        intentMemory: { threatTtlTicks: 45, preyTtlTicks: 90, foodTtlTicks: 180, allyTtlTicks: 60 },
        terminalHoming: { enabled: true, handoffRadius: null, requireWorldLos: true, minHoldTicks: 6 },
    },
    agentProfiles: {
        snake: {
            bodyPropId: "ball",
            headPropId: "snake_head",
            segmentCount: 3,
            leaderIndex: 0,
            linkSlack: 1.0,
            growDirX: -1,
            growDirY: 0,
            headMaxSpeed: 250,
            headFriction: 2.0,
            headAccel: 200,
            segmentFriction: 2.25,
            segmentDensity: 0.001,
            minAliveSegmentCount: 3,
            maxAliveSegmentCount: 12,
            metabolism: { hungerDrainMs: 30_000, foodValue: 0.5, growthCost: 1.0, starveShedIntervalMs: 10_000 },
            rivalBand: { maxSegmentGap: 2 },
            scoringEnv: { effortFallback: true },
            hungerBands: [
                { id: "satisfied", min: 0.66 },
                { id: "hungry", min: 0.33 },
                { id: "desperate", min: 0 },
            ],
            decisionWeights: { flee: 400, prey: 300, food: 340, seek_ally: 220, explore: 100 },
            factionCohesion: { arrivalRadius: 32, idealStopDist: 3, packBonus: 15, satisfiedBonus: 50, referenceSegmentCount: 3, maxSegmentScale: 10 },
            decisionPressure: {
                foodHungerBonus: 300,
                preyDesperationBonus: 250,
                enemySnakePreyValue: 1300,
                riskTolerance: { satisfied: 0, hungry: 0.4, desperate: 0.75 },
                effort: { costPerCell: { satisfied: 25, hungry: 20, desperate: 6 }, preyValue: { satisfied: 140, hungry: 300, desperate: 550 } },
            },
            sprint: {
                fleeSeverity: 0.5,
                speedMultiplier: 1.4,
                accelMultiplier: 1.4,
                hungerDrainMultiplier: 2.5,
                rules: [
                    { mode: "flee", rule: "severeOrLethalThreat", want: true, reason: "escape" },
                    { mode: "seek_food", rule: "severeNonLethalThreat", want: true, reason: "feed" },
                    { mode: "seek_prey", rule: "always", want: true, reason: "chase" },
                ],
            },
            decision: {
                scoreOrder: ["flee", "seek_prey", "seek_food", "seek_ally", "explore"],
                targetLost: { seek_prey: "prey", seek_food: "food", seek_ally: "ally" },
                remembered: [{ key: "threat" }, { key: "prey" }, { key: "food" }, { key: "ally" }, { key: "allyCount", allyCount: 1 }, { key: "allyCentroid", constant: null }],
                eventTargets: ["threat", "prey", "food", "ally"],
                slots: { threat: {}, prey: {}, food: {}, ally: { known: "engagedAlly" } },
                fields: {
                    allyCount: {
                        visible: { from: "allyCount", default: 0 },
                        known: { anchorSlot: "ally", matchWorldSlot: "ally", fromVisible: "allyCount", fromRemembered: "allyCount", whenMissing: 0 },
                    },
                    allyCentroid: {
                        visible: { from: "allyCentroid", default: null },
                        known: { anchorSlot: "ally", matchWorldSlot: "ally", fromVisible: "allyCentroid", whenMissing: null, whenNoMatch: null },
                    },
                },
                modes: {
                    flee: { scorer: "riskAdjustedFlee" },
                    seek_prey: { scorer: "preyWithEffort", slot: "prey" },
                    seek_food: { scorer: "foodWithHunger", slot: "food" },
                    seek_ally: { scorer: "regroupAlly", slot: "ally", cohesion: "snake", guards: ["requiresLeadworthy", "requiresSatisfied", "noThreat"] },
                    explore: { scorer: "constant", weightKey: "explore" },
                },
            },
            intent: SNAKE_INTENT,
        },
        flee_agent: {
            bodyPropId: "flee_ball",
            segmentCount: 1,
            leaderIndex: 0,
            faction: "bravo",
            teams: [
                { faction: "charlie", color: "#f1c40f" },
                { faction: "delta", color: "#2ecc71" },
            ],
            maxSpeed: 100,
            accel: 200,
            friction: null,
            initialHunger: 0.85,
            metabolism: { hungerDrainMs: 90_000, foodValue: 0.35 },
            scoringEnv: { sprint: true },
            hungerBands: [
                { id: "satisfied", min: 0.66 },
                { id: "hungry", min: 0.33 },
                { id: "desperate", min: 0 },
            ],
            sprint: {
                fleeSeverity: 0.5,
                speedMultiplier: 1.75,
                accelMultiplier: 1.5,
                hungerDrainMultiplier: 2.0,
                sprintFleeMinHunger: 0.1,
                rules: [
                    { mode: "flee", rule: "severeOrLethalThreat", guards: ["minHunger"], want: true, reason: "escape" },
                    { mode: "seek_food", rule: "severeNonLethalThreat", guards: ["minHunger", "bandDesperate"], want: true, reason: "race" },
                    { mode: "seek_enemy", rule: "always", want: true, reason: "attack" },
                ],
            },
            decisionWeights: { flee: 400, enemy: 420, food: 360, seek_ally: 280, explore: 100 },
            factionCohesion: { arrivalRadius: 24, idealStopDist: 2.5, packBonus: 20, satisfiedBonus: 60, fleePackBlend: 0.35, maxPackDistCells: 16 },
            decisionPressure: {
                foodHungerBonus: 280,
                sprintFleeMinHunger: 0.1,
                outnumberedFleeBonus: 0.4,
                sprintFoodCostPenalty: 40,
                riskTolerance: { satisfied: 0, hungry: 0.35, desperate: 0.65 },
                effort: { costPerCell: { satisfied: 22, hungry: 18, desperate: 8 } },
            },
            decision: {
                scoreOrder: ["flee", "seek_enemy", "seek_food", "seek_ally", "explore"],
                targetLost: { seek_enemy: "enemy", seek_food: "food", seek_ally: "ally" },
                remembered: [{ key: "threat" }, { key: "enemy", memoryKey: "prey" }, { key: "food" }, { key: "ally" }, { key: "allyCount", allyCount: 1 }, { key: "allyCentroid", constant: null }],
                eventTargets: ["threat", "food", "enemy", "ally"],
                slots: { threat: {}, enemy: { visibleFrom: "prey", memoryKey: "prey", hideVisibleWhenMemory: true, known: "visibleOrRemembered" }, food: {}, ally: { hideVisibleWhenMemory: true } },
                fields: {
                    threatCount: { visible: { from: "threatCount", default: 0 }, known: { fromVisible: "threatCount", default: 0 } },
                    allyCount: {
                        visible: { from: "allyCount", default: 0, ifMemory: { key: "ally", use: 0 } },
                        known: { visibleIfSlot: "ally", fromVisible: "allyCount", fromRemembered: "allyCount" },
                    },
                    allyCentroid: { visible: { from: "allyCentroid", default: null, ifMemory: { key: "ally", use: null } }, known: { fromVisible: "allyCentroid" } },
                },
                modes: {
                    flee: { scorer: "riskAdjustedFlee", mods: ["outnumberedFlee"] },
                    seek_enemy: { scorer: "reachTarget", slot: "enemy", weightKey: "enemy", guards: ["noThreat"] },
                    seek_food: { scorer: "foodWithHunger", slot: "food", guards: ["notSatisfied"] },
                    seek_ally: { scorer: "regroupAlly", slot: "ally", cohesion: "flee", guards: ["noThreat", "notDesperate"] },
                    explore: { scorer: "constant", weightKey: "explore" },
                },
            },
            intent: FLEE_INTENT,
        },
        squid: {
            bodyPropId: "ball",
            brainPropId: "snake_head",
            segmentCount: 3,
            leaderIndex: 1,
            armSegmentCount: 1,
            linkSlack: 1.0,
            growDirX: -1,
            growDirY: 0,
            brainMaxSpeed: 180,
            brainFriction: 2.25,
            brainAccel: 160,
            segmentFriction: 2.5,
            segmentDensity: 0.001,
            minAliveSegmentCount: 2,
            metabolism: { hungerDrainMs: 15_000, foodValue: 0.5 },
            rivalBand: { maxSegmentGap: 2 },
            scoringEnv: { effortFallback: true },
            hungerBands: [
                { id: "satisfied", min: 0.66 },
                { id: "hungry", min: 0.33 },
                { id: "desperate", min: 0 },
            ],
            decisionWeights: { flee: 360, prey: 400, food: 320, explore: 100 },
            factionCohesion: { referenceSegmentCount: 3 },
            decisionPressure: {
                foodHungerBonus: 320,
                preyDesperationBonus: 280,
                enemySnakePreyValue: 1200,
                riskTolerance: { satisfied: 0.1, hungry: 0.45, desperate: 0.8 },
                effort: { costPerCell: { satisfied: 28, hungry: 22, desperate: 8 }, preyValue: { satisfied: 160, hungry: 320, desperate: 580 } },
            },
            sprint: {
                fleeSeverity: 0.5,
                speedMultiplier: 1.35,
                accelMultiplier: 1.35,
                hungerDrainMultiplier: 2.2,
                rules: [
                    { mode: "flee", rule: "severeOrLethalThreat", want: true, reason: "escape" },
                    { mode: "seek_food", rule: "severeNonLethalThreat", want: true, reason: "feed" },
                    { mode: "seek_prey", rule: "always", want: true, reason: "attack" },
                ],
            },
            decision: {
                scoreOrder: ["flee", "seek_prey", "seek_food", "explore"],
                targetLost: { seek_prey: "prey", seek_food: "food" },
                remembered: [{ key: "threat" }, { key: "prey" }, { key: "food" }],
                eventTargets: ["threat", "prey", "food"],
                slots: { threat: {}, prey: {}, food: {} },
                fields: {},
                modes: {
                    flee: { scorer: "riskAdjustedFlee" },
                    seek_prey: { scorer: "preyWithEffort", slot: "prey" },
                    seek_food: { scorer: "foodWithHunger", slot: "food" },
                    explore: { scorer: "constant", weightKey: "explore" },
                },
            },
            intent: SQUID_INTENT,
        },
    },
};
